services:
  app:
    build: .
    env_file: .env.production
    ports:
      - "3000:3000"
    restart: unless-stopped
    command: npm run start
  scheduler:
    build: .
    env_file: .env.production
    restart: unless-stopped
    command: npm run worker:scheduler
