import React, { useCallback, useEffect, useState } from 'react';
import { ActivityIndicator, Pressable, RefreshControl, ScrollView, StyleSheet, Text, View } from 'react-native';

import { ApiError } from '@/api';
import { Screen } from '@/components';
import { cacheJson, readCachedJson } from '@/offline/cache';
import { bookmarkCurrentAffairs, createResource, getCurrentAffairs, refreshCurrentAffairs, type CurrentAffairsItem } from '@/api/upscProduct';
import { useTranslation } from '@/localization';
import type { MoreStackScreenProps } from '@/navigation/types';

export function CurrentAffairsScreen({ navigation }: MoreStackScreenProps<'Updates'>): React.JSX.Element {
    const t = useTranslation();
    const [items, setItems] = useState<CurrentAffairsItem[]>([]);
    const [loading, setLoading] = useState(true);
    const [refreshing, setRefreshing] = useState(false);
    const [error, setError] = useState<string | null>(null);
    const [actionMessage, setActionMessage] = useState<string | null>(null);
    const load = useCallback(async (): Promise<void> => { setError(null); try { const result = await getCurrentAffairs(); setItems(result.items); await cacheJson('current-affairs', result.items); } catch (err) { const cached = await readCachedJson<CurrentAffairsItem[]>('current-affairs'); if (cached) setItems(cached.value); setError(err instanceof ApiError ? err.message + ' ' + t('currentAffairs.cached') : t('currentAffairs.cached')); } }, [t]);
    useEffect(() => { void (async () => { await load(); setLoading(false); })(); }, [load]);
    const onRefresh = async (): Promise<void> => { setRefreshing(true); await load(); setRefreshing(false); };
    const markRead = async (item: CurrentAffairsItem): Promise<void> => { try { await bookmarkCurrentAffairs(item.id); setItems((list) => list.map((entry) => entry.id === item.id ? { ...entry, bookmark: { id: entry.bookmark?.id ?? item.id, read: true, notes: entry.bookmark?.notes ?? null } } : entry)); setActionMessage('Marked as read.'); } catch { setActionMessage('Could not mark this update as read. Try again.'); } };
    const saveForRevision = async (item: CurrentAffairsItem): Promise<void> => { try { await bookmarkCurrentAffairs(item.id, true, true); setItems((list) => list.map((entry) => entry.id === item.id ? { ...entry, bookmark: { id: entry.bookmark?.id ?? item.id, read: true, notes: entry.bookmark?.notes ?? null } } : entry)); setActionMessage('Saved to your revision queue.'); } catch { setActionMessage('Could not save this revision. Try again.'); } };
    const addNote = async (item: CurrentAffairsItem): Promise<void> => { try { await createResource({ title: `${item.title} — ${item.summary}`, type: 'NOTE', tags: ['current-affairs', ...item.syllabusTags] }); setActionMessage('Note added to Library.'); } catch { setActionMessage('Could not add the note. Try again.'); } };
    return <Screen title={t('currentAffairs.title')}><ScrollView contentContainerStyle={styles.scroll} refreshControl={<RefreshControl refreshing={refreshing} onRefresh={() => void onRefresh()} />}>{loading ? <ActivityIndicator color="#2563eb" /> : <><Text style={styles.intro}>Exam-linked updates, not an endless news feed. Save only what you want to recall.</Text><Pressable style={styles.refreshButton} onPress={() => void refreshCurrentAffairs().then(() => load()).catch(() => setError(t('currentAffairs.refreshError')))}><Text style={styles.refreshText}>{t('currentAffairs.refresh')}</Text></Pressable>{error ? <Text style={styles.error}>{error}</Text> : null}{actionMessage ? <Text style={styles.actionMessage}>{actionMessage}</Text> : null}{items.length === 0 ? <Text style={styles.muted}>{t('currentAffairs.noUpdates')}</Text> : items.map((item) => <View key={item.id} style={styles.card}><View style={styles.header}><Text style={styles.category}>{item.category}</Text><Text style={styles.date}>{item.publishedAt.slice(0, 10)}</Text></View><Text style={styles.title}>{item.title}</Text><Text style={styles.mapping}>{item.syllabusTags.length ? `Syllabus: ${item.syllabusTags.join(' · ')}` : `Syllabus: ${item.category}`}</Text><Text style={styles.relevance}>Prelims: {item.prelimsRelevance ?? 'MEDIUM'} · Mains: {item.mainsRelevance ?? 'MEDIUM'}</Text><Text style={styles.summary}>{item.summary}</Text><Text style={styles.source}>{item.sourceName}</Text><View style={styles.actions}><Pressable style={styles.readButton} onPress={() => void markRead(item)}><Text style={styles.readText}>{item.bookmark?.read ? t('currentAffairs.savedRead') : t('currentAffairs.markRead')}</Text></Pressable><Pressable style={styles.revisionButton} onPress={() => void saveForRevision(item)}><Text style={styles.revisionText}>Save for revision</Text></Pressable><Pressable style={styles.readButton} onPress={() => void addNote(item)}><Text style={styles.readText}>Add note</Text></Pressable><Pressable style={styles.readButton} onPress={() => navigation.getParent()?.navigate('Practice')}><Text style={styles.readText}>Practice related PYQs</Text></Pressable></View></View>)}</>}</ScrollView></Screen>;
}

const styles = StyleSheet.create({ scroll: { paddingBottom: 32 }, intro: { color: '#475569', lineHeight: 20, marginBottom: 10 }, error: { color: '#b91c1c', marginBottom: 12 }, actionMessage: { color: '#166534', backgroundColor: '#f0fdf4', borderRadius: 8, padding: 10, marginBottom: 12 }, muted: { color: '#6b7280', textAlign: 'center', marginTop: 20 }, refreshButton: { backgroundColor: '#eff6ff', padding: 10, borderRadius: 8, alignItems: 'center', marginBottom: 12 }, refreshText: { color: '#1d4ed8', fontWeight: '700' }, card: { borderWidth: 1, borderColor: '#e5e7eb', borderRadius: 12, padding: 14, marginBottom: 12 }, header: { flexDirection: 'row', justifyContent: 'space-between', marginBottom: 6 }, category: { fontSize: 12, color: '#2563eb', fontWeight: '800', textTransform: 'uppercase' }, date: { fontSize: 12, color: '#6b7280' }, title: { fontSize: 16, fontWeight: '800', color: '#111827', marginBottom: 6 }, mapping: { color: '#1d4ed8', marginTop: 7, fontWeight: '700', fontSize: 12 }, relevance: { color: '#475569', marginTop: 3, fontSize: 12 }, summary: { color: '#374151', lineHeight: 20, marginTop: 7 }, source: { marginTop: 8, color: '#6b7280', fontSize: 12 }, actions: { flexDirection: 'row', flexWrap: 'wrap', gap: 12, marginTop: 10 }, readButton: { alignSelf: 'flex-start', backgroundColor: '#eff6ff', paddingVertical: 7, paddingHorizontal: 10, borderRadius: 7 }, readText: { color: '#1d4ed8', fontSize: 12, fontWeight: '700' }, revisionButton: { alignSelf: 'flex-start', backgroundColor: '#f5f3ff', paddingVertical: 7, paddingHorizontal: 10, borderRadius: 7 }, revisionText: { color: '#7c3aed', fontSize: 12, fontWeight: '800' } });
