import React, { useCallback, useEffect, useRef, useState } from 'react';
import { StyleSheet, Text, TextInput, View } from 'react-native';

import { getCommunityMessages, getSharedDashboard, reportCommunityContent, sendCommunityMessage, type CommunityMessage, type SharedDashboard } from '@/api/upscProduct';
import type { MoreStackScreenProps } from '@/navigation/types';
import { Action, Body, Card, Eyebrow, FeatureScreen, Heading, Muted, Progress, featureStyles, palette } from '@/screens/design/FeatureUi';

export function CommunityChatScreen({ route, navigation }: MoreStackScreenProps<'CommunityChat'>): React.JSX.Element {
    const { userId, label = 'Study buddy' } = route.params; const [messages, setMessages] = useState<CommunityMessage[]>([]); const [body, setBody] = useState(''); const [error, setError] = useState<string | null>(null); const latest = useRef<string | undefined>(undefined);
    const load = useCallback(async () => { try { const result = await getCommunityMessages(userId, latest.current); setMessages((current) => Array.from(new Map([...current, ...result.messages].map((item) => [item.id, item])).values()).sort((a, b) => a.createdAt.localeCompare(b.createdAt))); latest.current = result.messages.at(-1)?.createdAt ?? latest.current; } catch (reason) { setError(reason instanceof Error ? reason.message : 'Messages could not sync.'); } }, [userId]);
    useEffect(() => { void load(); const timer = setInterval(() => void load(), 10_000); return () => clearInterval(timer); }, [load]);
    const send = async (): Promise<void> => { if (!body.trim()) return; try { await sendCommunityMessage(userId, body.trim()); setBody(''); await load(); } catch (reason) { setError(reason instanceof Error ? reason.message : 'Message could not send.'); } };
    return <FeatureScreen title={label} subtitle="Private buddy conversation • efficient live/polling sync"><Card tone="brand"><Eyebrow>SHARED TARGET</Eyebrow><Heading>90 focused minutes</Heading><Body>Keep the conversation about accountability and study progress.</Body><Action label="View 7-day dashboard" secondary onPress={() => navigation.navigate('SharedStudyDashboard', { userId, label })} /></Card>{messages.map((message) => <View key={message.id} style={[styles.bubble, message.recipientId === userId ? styles.mine : styles.theirs]}><Body>{message.body}</Body><Muted>{new Date(message.createdAt).toLocaleTimeString([], { hour: '2-digit', minute: '2-digit' })}</Muted><Text style={styles.report} onPress={() => void reportCommunityContent({ messageId: message.id, reason: 'User report from buddy chat' })}>Report</Text></View>)}<TextInput style={featureStyles.input} value={body} onChangeText={setBody} placeholder="Message your study buddy…" /><Action label="Send" disabled={!body.trim()} onPress={() => void send()} />{error ? <Card tone="warning"><Body>{error}</Body></Card> : null}</FeatureScreen>;
}

export function SharedStudyDashboardScreen({ route }: MoreStackScreenProps<'SharedStudyDashboard'>): React.JSX.Element {
    const { userId, label = 'Study buddy' } = route.params; const [dashboard, setDashboard] = useState<SharedDashboard | null>(null); const [error, setError] = useState<string | null>(null);
    const load = useCallback(async () => { try { setDashboard((await getSharedDashboard(userId)).dashboard); } catch (reason) { setError(reason instanceof Error ? reason.message : 'Shared dashboard is unavailable.'); } }, [userId]); useEffect(() => { void load(); }, [load]);
    const max = Math.max(1, ...(dashboard?.audits.map((item) => Math.max(item.actualMin, item.plannedMin)) ?? [1]));
    return <FeatureScreen title={`${label} + You`} subtitle="Shared last 7 days • private to both buddies">{dashboard ? <><Card tone="brand"><Text style={featureStyles.big}>{dashboard.focusMinutes} focused minutes</Text><Body>{dashboard.focusSessions} sessions • no public ranking or comparison pressure</Body></Card><Heading>Daily shared consistency</Heading>{dashboard.audits.slice(-7).map((audit) => <Card key={audit.date}><View style={featureStyles.between}><Heading>{new Date(audit.date).toLocaleDateString([], { weekday: 'short' })}</Heading><Muted>{audit.actualMin}/{audit.plannedMin} min</Muted></View><Progress value={audit.actualMin / max * 100} /></Card>)}<Card tone="success"><Heading>Upcoming shared rhythm</Heading>{dashboard.upcomingBlocks.slice(0, 3).map((block) => <Body key={block.startTime}>{new Date(block.startTime).toLocaleString()} • {block.durationMin} min • {block.sessionType}</Body>)}</Card></> : <Card tone={error ? 'warning' : 'plain'}><Heading>{error ?? 'Loading shared progress…'}</Heading>{error ? <Action label="Retry" secondary onPress={() => void load()} /> : null}</Card>}</FeatureScreen>;
}

const styles = StyleSheet.create({ bubble: { maxWidth: '86%', borderRadius: 16, padding: 12, marginBottom: 9 }, mine: { backgroundColor: palette.brandSoft, alignSelf: 'flex-end' }, theirs: { backgroundColor: '#f3f4f6', alignSelf: 'flex-start' }, report: { color: '#b91c1c', fontSize: 11, marginTop: 4 } });
