import React, { useCallback, useEffect, useRef, useState } from 'react';
import { StyleSheet, Text, TextInput, View } from 'react-native';

import { getCommunityMessages, getSharedDashboard, reportCommunityContent, sendCommunityMessage, type CommunityMessage, type SharedDashboard } from '@/api/upscProduct';
import type { MoreStackScreenProps } from '@/navigation/types';
import { interpolate, useTranslation } from '@/localization';
import { Action, Body, Card, Eyebrow, FeatureScreen, Heading, Muted, Progress, featureStyles, palette } from '@/screens/design/FeatureUi';

export function CommunityChatScreen({ route, navigation }: MoreStackScreenProps<'CommunityChat'>): React.JSX.Element {
    const t = useTranslation();
    const { userId, label = t('communityDetail.studyBuddy') } = route.params; const [messages, setMessages] = useState<CommunityMessage[]>([]); const [body, setBody] = useState(''); const [error, setError] = useState<string | null>(null); const latest = useRef<string | undefined>(undefined);
    const load = useCallback(async () => { try { const result = await getCommunityMessages(userId, latest.current); setMessages((current) => Array.from(new Map([...current, ...result.messages].map((item) => [item.id, item])).values()).sort((a, b) => a.createdAt.localeCompare(b.createdAt))); latest.current = result.messages.at(-1)?.createdAt ?? latest.current; } catch (reason) { setError(reason instanceof Error ? reason.message : t('communityDetail.syncError')); } }, [t, userId]);
    useEffect(() => { void load(); const timer = setInterval(() => void load(), 10_000); return () => clearInterval(timer); }, [load]);
    const send = async (): Promise<void> => { if (!body.trim()) return; try { await sendCommunityMessage(userId, body.trim()); setBody(''); await load(); } catch (reason) { setError(reason instanceof Error ? reason.message : t('communityDetail.sendError')); } };
    return <FeatureScreen title={label} subtitle={t('communityDetail.chatSubtitle')}><Card tone="brand"><Eyebrow>{t('communityDetail.sharedTarget')}</Eyebrow><Heading>{t('communityDetail.ninetyMinutes')}</Heading><Body>{t('communityDetail.keepAccountable')}</Body><Action label={t('communityDetail.viewDashboard')} secondary onPress={() => navigation.navigate('SharedStudyDashboard', { userId, label })} /></Card>{messages.map((message) => <View key={message.id} style={[styles.bubble, message.recipientId === userId ? styles.mine : styles.theirs]}><Body>{message.body}</Body><Muted>{new Date(message.createdAt).toLocaleTimeString([], { hour: '2-digit', minute: '2-digit' })}</Muted><Text style={styles.report} onPress={() => void reportCommunityContent({ messageId: message.id, reason: 'User report from buddy chat' })}>{t('communityDetail.report')}</Text></View>)}<TextInput style={featureStyles.input} value={body} onChangeText={setBody} placeholder={t('communityDetail.messagePlaceholder')} /><Action label={t('communityDetail.send')} disabled={!body.trim()} onPress={() => void send()} />{error ? <Card tone="warning"><Body>{error}</Body></Card> : null}</FeatureScreen>;
}

export function SharedStudyDashboardScreen({ route }: MoreStackScreenProps<'SharedStudyDashboard'>): React.JSX.Element {
    const t = useTranslation();
    const { userId, label = t('communityDetail.studyBuddy') } = route.params; const [dashboard, setDashboard] = useState<SharedDashboard | null>(null); const [error, setError] = useState<string | null>(null);
    const load = useCallback(async () => { try { setDashboard((await getSharedDashboard(userId)).dashboard); } catch (reason) { setError(reason instanceof Error ? reason.message : t('communityDetail.dashboardError')); } }, [t, userId]); useEffect(() => { void load(); }, [load]);
    const max = Math.max(1, ...(dashboard?.audits.map((item) => Math.max(item.actualMin, item.plannedMin)) ?? [1]));
    return <FeatureScreen title={interpolate(t('communityDetail.withYou'), { label })} subtitle={t('communityDetail.dashboardSubtitle')}>{dashboard ? <><Card tone="brand"><Text style={featureStyles.big}>{interpolate(t('communityDetail.focusedMinutes'), { count: dashboard.focusMinutes })}</Text><Body>{interpolate(t('communityDetail.sessionsNote'), { count: dashboard.focusSessions })}</Body></Card><Heading>{t('communityDetail.dailyConsistency')}</Heading>{dashboard.audits.slice(-7).map((audit) => <Card key={audit.date}><View style={featureStyles.between}><Heading>{new Date(audit.date).toLocaleDateString([], { weekday: 'short' })}</Heading><Muted>{interpolate(t('today.minutes'), { m: `${audit.actualMin}/${audit.plannedMin}` })}</Muted></View><Progress value={audit.actualMin / max * 100} /></Card>)}<Card tone="success"><Heading>{t('communityDetail.upcomingRhythm')}</Heading>{dashboard.upcomingBlocks.slice(0, 3).map((block) => <Body key={block.startTime}>{new Date(block.startTime).toLocaleString()} • {interpolate(t('today.minutes'), { m: block.durationMin })} • {block.sessionType}</Body>)}</Card></> : <Card tone={error ? 'warning' : 'plain'}><Heading>{error ?? t('communityDetail.loading')}</Heading>{error ? <Action label={t('common.retry')} secondary onPress={() => void load()} /> : null}</Card>}</FeatureScreen>;
}

const styles = StyleSheet.create({ bubble: { maxWidth: '86%', borderRadius: 16, padding: 12, marginBottom: 9 }, mine: { backgroundColor: palette.brandSoft, alignSelf: 'flex-end' }, theirs: { backgroundColor: '#f3f4f6', alignSelf: 'flex-start' }, report: { color: '#b91c1c', fontSize: 11, marginTop: 4 } });
