import React, { useCallback, useEffect, useMemo, useState } from 'react';
import { ActivityIndicator, Linking, Pressable, Share, StyleSheet, Text, TextInput, View } from 'react-native';

import {
    createConceptMap, createDoubt, createFormula, createRecallDrillAttempt, createRecoveryPlan, exportDoubtsCsv,
    getConceptMaps, getCounselling, getDoubts, getExamChecklist, getFormulas, getRevisionCards, getWellbeingInsights,
    logAnxietyProtocol, predictRoleFit, reviewRevisionCard, savePacing, simulateStrategy, submitAnswerWriting,
    updateExamChecklist, connectCoaching, type AnswerWritingAttempt, type ChecklistItem, type ConceptMap, type DoubtItem,
    type FormulaItem, type RevisionCard, type WellbeingInsights,
} from '@/api/upscProduct';
import { interpolate, useTranslation } from '@/localization';
import { Action, Body, Card, Chip, Eyebrow, FeatureScreen, Heading, Muted, Progress, featureStyles, palette } from '@/screens/design/FeatureUi';

function useMessage(): [string | null, (promise: Promise<unknown>, success: string) => Promise<void>] {
    const t = useTranslation();
    const [message, setMessage] = useState<string | null>(null);
    const run = useCallback(async (promise: Promise<unknown>, success: string) => { setMessage(null); try { await promise; setMessage(success); } catch (error) { setMessage(error instanceof Error ? error.message : t('focused.actionError')); } }, [t]);
    return [message, run];
}
function Message({ value }: { value: string | null }): React.JSX.Element | null { return value ? <Card tone="brand"><Body>{value}</Body></Card> : null; }

export function RecallStudioScreen(): React.JSX.Element {
    const t = useTranslation();
    const [cards, setCards] = useState<RevisionCard[]>([]); const [index, setIndex] = useState(0); const [revealed, setRevealed] = useState(false); const [loading, setLoading] = useState(true); const [message, run] = useMessage();
    const load = useCallback(async () => { setLoading(true); try { setCards((await getRevisionCards(true)).cards); setIndex(0); setRevealed(false); } finally { setLoading(false); } }, []);
    useEffect(() => { void load(); }, [load]); const card = cards[index];
    const rate = async (rating: 1 | 2 | 3 | 4): Promise<void> => { if (!card) return; await run(reviewRevisionCard(card.id, rating), t('focused.nextReviewRating')); setRevealed(false); setIndex((value) => Math.min(value + 1, cards.length)); };
    return <FeatureScreen title={t('focused.recallTitle')} subtitle={interpolate(t('focused.recallSubtitle'), { count: cards.length })}>{loading ? <ActivityIndicator color={palette.brand} /> : card ? <Card tone="brand"><Eyebrow>{card.revisionPhase ?? t('focused.activeRecall')} • {interpolate(t('focused.cardOf'), { current: index + 1, total: cards.length })}</Eyebrow><Heading>{card.title}</Heading><Text style={styles.prompt}>{card.prompt}</Text>{revealed ? <Card tone="plain"><Eyebrow>{t('focused.answer')}</Eyebrow><Body>{card.answer}</Body></Card> : <Action label={t('tools.revealAnswer')} onPress={() => setRevealed(true)} />}{revealed ? <View style={featureStyles.row}>{([1, 2, 3, 4] as const).map((rating) => <Chip key={rating} label={t((['tools.rateAgain', 'tools.rateHard', 'tools.rateGood', 'tools.rateEasy'] as const)[rating - 1]!)} onPress={() => void rate(rating)} />)}</View> : null}</Card> : <Card tone="success"><Heading>{t('focused.caughtUp')}</Heading><Muted>{t('focused.noCardsDue')}</Muted></Card>}<Message value={message} /></FeatureScreen>;
}

export function FormulaSprintScreen(): React.JSX.Element {
    const t = useTranslation();
    const [items, setItems] = useState<FormulaItem[]>([]); const [index, setIndex] = useState(0); const [seconds, setSeconds] = useState(300); const [running, setRunning] = useState(false); const [revealed, setRevealed] = useState(false); const [correct, setCorrect] = useState(0); const [title, setTitle] = useState(''); const [expression, setExpression] = useState(''); const [message, run] = useMessage();
    const load = useCallback(async () => setItems((await getFormulas()).items), []); useEffect(() => { void load(); }, [load]);
    useEffect(() => { if (!running || seconds <= 0) return; const timer = setInterval(() => setSeconds((value) => Math.max(0, value - 1)), 1000); return () => clearInterval(timer); }, [running, seconds]);
    useEffect(() => { if (running && seconds === 0) { setRunning(false); void run(createRecallDrillAttempt({ sourceType: 'FORMULA', itemCount: items.length, durationSec: 300, correct, revealed: index }), interpolate(t('tools.sprintComplete'), { correct, total: items.length })); } }, [correct, index, items.length, run, running, seconds]);
    const answer = (gotIt: boolean): void => { const next = correct + (gotIt ? 1 : 0); setCorrect(next); if (index >= items.length - 1) { setRunning(false); void run(createRecallDrillAttempt({ sourceType: 'FORMULA', itemCount: items.length, durationSec: 300 - seconds, correct: next, revealed: items.length }), interpolate(t('tools.sprintComplete'), { correct: next, total: items.length })); } else { setIndex((value) => value + 1); setRevealed(false); } };
    const current = items[index];
    return <FeatureScreen title={t('focused.sprintTitle')} subtitle={t('focused.sprintSubtitle')}><Card><Heading>{t('focused.addFormula')}</Heading><TextInput style={featureStyles.input} value={title} onChangeText={setTitle} placeholder={t('tools.formulaTitle')} /><TextInput style={featureStyles.input} value={expression} onChangeText={setExpression} placeholder={t('tools.formulaExpression')} /><Action label={t('tools.saveFormula')} disabled={!title.trim() || !expression.trim()} onPress={() => void run(createFormula({ title: title.trim(), expression: expression.trim() }).then(load), t('tools.formulaSaved'))} /></Card>{!running ? <Card tone="brand"><Heading>{interpolate(t('focused.formulasReady'), { count: items.length })}</Heading><Action label={t('focused.startSprint')} disabled={!items.length} onPress={() => { setIndex(0); setCorrect(0); setSeconds(300); setRevealed(false); setRunning(true); }} /></Card> : current ? <Card tone="brand"><View style={featureStyles.between}><Eyebrow>{interpolate(t('focused.formulaOf'), { current: index + 1, total: items.length })}</Eyebrow><Text style={styles.timer}>{Math.floor(seconds / 60)}:{String(seconds % 60).padStart(2, '0')}</Text></View><Text style={styles.prompt}>{current.title}</Text>{revealed ? <Card><Eyebrow>{t('focused.answer')}</Eyebrow><Body>{current.expression}</Body></Card> : <Action label={t('tools.revealExpression')} onPress={() => setRevealed(true)} />}{revealed ? <View style={featureStyles.row}><Action label={t('tools.gotIt')} onPress={() => answer(true)} /><Action label={t('tools.needsReview')} secondary onPress={() => answer(false)} /></View> : null}</Card> : null}<Message value={message} /></FeatureScreen>;
}

export function ConceptMapBuilderScreen(): React.JSX.Element {
    const t = useTranslation();
    const [maps, setMaps] = useState<ConceptMap[]>([]); const [title, setTitle] = useState(''); const [nodes, setNodes] = useState(''); const [relations, setRelations] = useState(''); const [message, run] = useMessage();
    const load = useCallback(async () => setMaps((await getConceptMaps()).maps), []); useEffect(() => { void load(); }, [load]);
    const nodeItems = useMemo(() => nodes.split(',').map((value) => value.trim()).filter(Boolean), [nodes]); const edgeItems = useMemo(() => relations.split(',').map((value) => value.split('->').map((part) => part.trim())).filter(([from, to]) => from && to), [relations]);
    const save = async (): Promise<void> => { await run(createConceptMap({ title: title.trim(), nodes: nodeItems.map((label) => ({ id: label.toLowerCase().replace(/\s+/g, '-'), label })), edges: edgeItems.map(([from, to]) => ({ from, to, label: t('focused.relatesTo') })) }).then(load), t('tools.mapSaved')); };
    return <FeatureScreen title={t('focused.mapScreenTitle')} subtitle={t('focused.mapSubtitle')}><Card><TextInput style={featureStyles.input} value={title} onChangeText={setTitle} placeholder={t('tools.mapTitle')} /><TextInput style={featureStyles.input} value={nodes} onChangeText={setNodes} placeholder={t('focused.conceptsPlaceholder')} /><TextInput style={featureStyles.input} value={relations} onChangeText={setRelations} placeholder={t('focused.relationsPlaceholder')} /><View style={styles.map}>{nodeItems.map((node) => <Chip key={node} label={node} selected />)}{edgeItems.map(([from, to], index) => <Body key={`${index}-${from}`}>{from} → {to}</Body>)}</View><View style={featureStyles.row}><Action label={t('tools.saveMap')} disabled={!title.trim() || nodeItems.length < 2} onPress={() => void save()} /><Action label={t('ai.export')} secondary disabled={!nodeItems.length} onPress={() => void Share.share({ title: title || t('focused.conceptMap'), message: `${title}\n${nodeItems.join(' • ')}\n${edgeItems.map(([a, b]) => `${a} → ${b}`).join('\n')}` })} /></View></Card>{maps.slice(0, 4).map((map) => <Card key={map.id} tone="revision"><Heading>{map.title}</Heading><Muted>{interpolate(t('tools.mapSummary'), { concepts: Array.isArray(map.nodes) ? map.nodes.length : 0, relationships: Array.isArray(map.edges) ? map.edges.length : 0 })}</Muted></Card>)}<Message value={message} /></FeatureScreen>;
}

export function PracticeLabScreen(): React.JSX.Element {
    const t = useTranslation();
    const [questions, setQuestions] = useState('10'); const [target, setTarget] = useState('600'); const [remaining, setRemaining] = useState(0); const [answered, setAnswered] = useState(0); const [correct, setCorrect] = useState(0); const [skipped, setSkipped] = useState(0); const [simulation, setSimulation] = useState<string[]>([]); const [message, run] = useMessage();
    useEffect(() => { if (remaining <= 0) return; const timer = setInterval(() => setRemaining((value) => Math.max(0, value - 1)), 1000); return () => clearInterval(timer); }, [remaining]);
    const finish = async (nextCorrect = correct, nextSkipped = skipped): Promise<void> => { const count = Math.max(1, Number(questions)); await run(savePacing({ questionCount: count, targetSeconds: Number(target), actualSeconds: Number(target) - remaining, correct: nextCorrect, skipped: nextSkipped }), t('focused.paceSaved')); setRemaining(0); };
    const record = (kind: 'correct' | 'skip'): void => { const nextAnswered = answered + 1; const nextCorrect = correct + (kind === 'correct' ? 1 : 0); const nextSkipped = skipped + (kind === 'skip' ? 1 : 0); setAnswered(nextAnswered); setCorrect(nextCorrect); setSkipped(nextSkipped); if (nextAnswered >= Number(questions)) void finish(nextCorrect, nextSkipped); };
    return <FeatureScreen title={t('focused.labTitle')} subtitle={t('focused.labSubtitle')}><Card tone="brand"><View style={featureStyles.between}><Heading>{t('focused.livePacing')}</Heading><Text style={styles.timer}>{Math.floor(remaining / 60)}:{String(remaining % 60).padStart(2, '0')}</Text></View>{remaining ? <><Eyebrow>{interpolate(t('focused.questionOf'), { current: Math.min(answered + 1, Number(questions)), total: questions })}</Eyebrow><Body>{t('focused.readDecide')}</Body><View style={featureStyles.row}><Action label={t('tools.correctNext')} onPress={() => record('correct')} /><Action label={t('tools.skipNext')} secondary onPress={() => record('skip')} /></View></> : <><TextInput style={featureStyles.input} value={questions} onChangeText={setQuestions} keyboardType="number-pad" placeholder={t('tools.questions')} /><TextInput style={featureStyles.input} value={target} onChangeText={setTarget} keyboardType="number-pad" placeholder={t('tools.totalSeconds')} /><Action label={t('focused.startLivePacing')} onPress={() => { setAnswered(0); setCorrect(0); setSkipped(0); setRemaining(Math.max(30, Number(target))); }} /></>}</Card><Card><Heading>{t('focused.strategySimulator')}</Heading><Action label={t('focused.simulateAttempt')} onPress={() => void run(simulateStrategy({ questionCount: Number(questions), totalTimeSec: Number(target), targetAttempted: Math.max(1, Number(questions) - 2) }).then(({ simulation: result }) => setSimulation(result.advice)), t('focused.strategyCalculated'))} />{simulation.map((item) => <Body key={item}>• {item}</Body>)}</Card><Message value={message} /></FeatureScreen>;
}

export function AnswerWritingCanvasScreen(): React.JSX.Element {
    const t = useTranslation();
    const [prompt, setPrompt] = useState(''); const [answer, setAnswer] = useState(''); const [seconds, setSeconds] = useState(600); const [running, setRunning] = useState(false); const [review, setReview] = useState<AnswerWritingAttempt | null>(null); const [selfReview, setSelfReview] = useState<Record<string, boolean>>({}); const [message, run] = useMessage(); const wordCount = answer.trim() ? answer.trim().split(/\s+/).length : 0;
    useEffect(() => { if (!running || seconds <= 0) return; const timer = setInterval(() => setSeconds((value) => Math.max(0, value - 1)), 1000); return () => clearInterval(timer); }, [running, seconds]);
    const submit = async (): Promise<void> => { await run(submitAnswerWriting({ prompt, answerText: answer, timeTakenSec: 600 - seconds }).then(({ attempt }) => setReview(attempt)), t('focused.savedToJournal')); setRunning(false); };
    const checklist = [t('focused.checkDirective'), t('focused.checkIntro'), t('focused.checkDimensions'), t('focused.checkExamples'), t('focused.checkConclusion')];
    return <FeatureScreen title={t('focused.writingTitle')} subtitle={t('focused.writingSubtitle')}><Card><TextInput style={featureStyles.input} value={prompt} onChangeText={setPrompt} placeholder={t('focused.directivePlaceholder')} /><View style={featureStyles.between}><Text style={styles.timer}>{interpolate(t('focused.timeLeft'), { time: `${Math.floor(seconds / 60)}:${String(seconds % 60).padStart(2, '0')}` })}</Text><Muted>{interpolate(t('focused.wordsOf'), { count: wordCount, limit: 150 })}</Muted></View><TextInput style={[featureStyles.input, featureStyles.multiline, styles.answerInput]} value={answer} onChangeText={setAnswer} multiline placeholder={t('focused.answerPlaceholder')} />{!running ? <Action label={t('focused.startAnswer')} disabled={!prompt.trim()} onPress={() => { setSeconds(600); setRunning(true); setSelfReview({}); }} /> : <Action label={t('focused.saveToJournal')} disabled={!answer.trim()} onPress={() => void submit()} />}</Card>{review ? <><Card tone="revision"><Eyebrow>{t('focused.selfReview')}</Eyebrow><Heading>{t('focused.checkStructure')}</Heading>{checklist.map((item) => <Pressable key={item} style={styles.checkItem} onPress={() => setSelfReview((value) => ({ ...value, [item]: !value[item] }))}><Text style={styles.checkText}>{selfReview[item] ? '✓' : '○'} {item}</Text></Pressable>)}</Card><Card tone="success"><Eyebrow>{review.feedback.source === 'AI' ? t('tools.aiAssisted') : t('tools.rubric')}</Eyebrow><Text style={featureStyles.score}>{review.feedback.score}/100</Text><Body>{review.feedback.demandAnalysis}</Body>{Object.entries(review.feedback.criteria).map(([label, value]) => <View key={label}><View style={featureStyles.between}><Muted>{label}</Muted><Muted>{value}/20</Muted></View><Progress value={value * 5} /></View>)}</Card></> : null}<Message value={message} /></FeatureScreen>;
}

export function WellbeingProtocolScreen(): React.JSX.Element {
    const t = useTranslation();
    const [insights, setInsights] = useState<WellbeingInsights | null>(null); const [checklist, setChecklist] = useState<ChecklistItem[]>([]); const [message, run] = useMessage(); const load = useCallback(async () => { const [wellbeing, list] = await Promise.all([getWellbeingInsights(), getExamChecklist()]); setInsights(wellbeing); setChecklist(list.items); }, []); useEffect(() => { void load(); }, [load]);
    return <FeatureScreen title={t('focused.wellbeingTitle')} subtitle={t('focused.wellbeingSubtitle')}><Card tone={insights?.risk === 'HIGH' ? 'warning' : 'brand'}><Eyebrow>{t('focused.loadSignal')}</Eyebrow><Heading>{insights ? interpolate(t('focused.burnoutRisk'), { risk: insights.risk }) : t('focused.readingLoad')}</Heading>{insights ? <Body>{interpolate(t('focused.loadSummary'), { energy: insights.signals.averageEnergy.toFixed(1), stress: insights.signals.averageStress.toFixed(1), days: insights.signals.heavyStudyDays })}</Body> : <ActivityIndicator color={palette.brand} />}<Action label={t('focused.applyRecovery')} onPress={() => void run(createRecoveryPlan('Rolling-load recovery requested from wellbeing screen').then(load), t('focused.recoveryAdded'))} /></Card><Card><Heading>{t('focused.needRelief')}</Heading><View style={featureStyles.row}><Action label={t('focused.boxBreathing2')} secondary onPress={() => void run(logAnxietyProtocol('BOX_BREATHING', 120), t('focused.breathingDone'))} /><Action label={t('focused.grounding3')} secondary onPress={() => void run(logAnxietyProtocol('GROUNDING_5_4_3_2_1', 180), t('focused.groundingDone'))} /></View></Card><Card><Heading>{t('tools.checklistHeading')}</Heading>{checklist.map((item) => <Action key={item.id} label={`${item.completed ? '✓' : '○'} ${item.label}`} secondary onPress={() => void run(updateExamChecklist(item.id, !item.completed).then(load), t('tools.checklistUpdated'))} />)}</Card><Message value={message} /></FeatureScreen>;
}

export function GuidanceDoubtsScreen(): React.JSX.Element {
    const t = useTranslation();
    const [doubts, setDoubts] = useState<DoubtItem[]>([]); const [title, setTitle] = useState(''); const [question, setQuestion] = useState(''); const [tags, setTags] = useState(''); const [url, setUrl] = useState(''); const [role, setRole] = useState<string | null>(null); const [message, run] = useMessage(); const load = useCallback(async () => setDoubts((await getDoubts()).doubts), []); useEffect(() => { void load(); }, [load]);
    return <FeatureScreen title={t('focused.guidanceTitle')} subtitle={t('focused.guidanceSubtitle')}><Card tone="revision"><Eyebrow>{t('focused.suggestedExploration')}</Eyebrow><Heading>{role ?? t('focused.roleReady')}</Heading><Muted>{t('focused.heuristic')}</Muted><Action label={t('tools.suggestRole')} secondary onPress={() => void run(Promise.all([getCounselling(), predictRoleFit({ interests: ['analysis', 'administration'] })]).then(([, result]) => setRole(String((result.predictions[0] as Record<string, unknown> | undefined)?.name ?? t('focused.exploreRoles')))), t('focused.roleRefreshed'))} /></Card><Card><Heading>{t('focused.logDoubt')}</Heading><TextInput style={featureStyles.input} value={title} onChangeText={setTitle} placeholder={t('tools.doubtTitle')} /><TextInput style={[featureStyles.input, featureStyles.multiline]} value={question} onChangeText={setQuestion} multiline placeholder={t('focused.whatUnclear')} /><TextInput style={featureStyles.input} value={tags} onChangeText={setTags} placeholder={t('focused.tagsPlaceholder')} /><TextInput style={featureStyles.input} value={url} onChangeText={setUrl} placeholder={t('focused.urlPlaceholder')} autoCapitalize="none" /><Action label={t('tools.saveDoubt')} disabled={!title.trim() || !question.trim()} onPress={() => void run(createDoubt({ title, question, tags: tags.split(',').map((x) => x.trim()).filter(Boolean), resourceUrls: url ? [url] : [] }).then(load), t('tools.doubtSaved'))} /><Action label={t('focused.exportCsv')} secondary onPress={() => void run(exportDoubtsCsv().then((csv) => Share.share({ title: t('tools.doubtsShareTitle'), message: csv })), t('focused.csvReady'))} /></Card>{doubts.slice(0, 5).map((item) => <Card key={item.id}><Heading>{item.title}</Heading><Muted>{item.status} • {item.tags.join(', ')}</Muted>{item.resourceUrls.map((link) => <Text key={link} style={featureStyles.link} onPress={() => void Linking.openURL(link)}>{t('focused.openResource')}</Text>)}</Card>)}<Card><Heading>{t('focused.coachingSync')}</Heading><Muted>{t('focused.coachingSafe')}</Muted><Action label={t('focused.connectSafely')} secondary onPress={() => void run(connectCoaching('MANUAL_PROVIDER'), t('tools.coachingConnected'))} /></Card><Message value={message} /></FeatureScreen>;
}

const styles = StyleSheet.create({ prompt: { color: palette.ink, fontSize: 18, lineHeight: 25, fontWeight: '800', marginVertical: 12 }, timer: { color: palette.brandText, fontSize: 18, fontWeight: '800' }, map: { minHeight: 150, borderWidth: 1, borderColor: palette.border, borderRadius: 16, padding: 14, gap: 10, marginTop: 4 }, answerInput: { minHeight: 260 }, checkItem: { borderTopWidth: 1, borderTopColor: palette.border, paddingVertical: 10 }, checkText: { color: palette.ink, fontWeight: '700' } });
