import React, { useCallback, useEffect, useMemo, useState } from 'react';
import { ActivityIndicator, Linking, Pressable, Share, StyleSheet, Text, TextInput, View } from 'react-native';

import {
    createConceptMap, createDoubt, createFormula, createRecallDrillAttempt, createRecoveryPlan, exportDoubtsCsv,
    getConceptMaps, getCounselling, getDoubts, getExamChecklist, getFormulas, getRevisionCards, getWellbeingInsights,
    logAnxietyProtocol, predictRoleFit, reviewRevisionCard, savePacing, simulateStrategy, submitAnswerWriting,
    updateExamChecklist, connectCoaching, type AnswerWritingAttempt, type ChecklistItem, type ConceptMap, type DoubtItem,
    type FormulaItem, type RevisionCard, type WellbeingInsights,
} from '@/api/upscProduct';
import { Action, Body, Card, Chip, Eyebrow, FeatureScreen, Heading, Muted, Progress, featureStyles, palette } from '@/screens/design/FeatureUi';

function useMessage(): [string | null, (promise: Promise<unknown>, success: string) => Promise<void>] {
    const [message, setMessage] = useState<string | null>(null);
    const run = useCallback(async (promise: Promise<unknown>, success: string) => { setMessage(null); try { await promise; setMessage(success); } catch (error) { setMessage(error instanceof Error ? error.message : 'Action could not be completed.'); } }, []);
    return [message, run];
}
function Message({ value }: { value: string | null }): React.JSX.Element | null { return value ? <Card tone="brand"><Body>{value}</Body></Card> : null; }

export function RecallStudioScreen(): React.JSX.Element {
    const [cards, setCards] = useState<RevisionCard[]>([]); const [index, setIndex] = useState(0); const [revealed, setRevealed] = useState(false); const [loading, setLoading] = useState(true); const [message, run] = useMessage();
    const load = useCallback(async () => { setLoading(true); try { setCards((await getRevisionCards(true)).cards); setIndex(0); setRevealed(false); } finally { setLoading(false); } }, []);
    useEffect(() => { void load(); }, [load]); const card = cards[index];
    const rate = async (rating: 1 | 2 | 3 | 4): Promise<void> => { if (!card) return; await run(reviewRevisionCard(card.id, rating), 'Next review scheduled from your rating.'); setRevealed(false); setIndex((value) => Math.min(value + 1, cards.length)); };
    return <FeatureScreen title="Recall studio" subtitle={`Due today: ${cards.length} cards • reviews adapt to your rating.`}>{loading ? <ActivityIndicator color={palette.brand} /> : card ? <Card tone="brand"><Eyebrow>{card.revisionPhase ?? 'ACTIVE RECALL'} • CARD {index + 1} OF {cards.length}</Eyebrow><Heading>{card.title}</Heading><Text style={styles.prompt}>{card.prompt}</Text>{revealed ? <Card tone="plain"><Eyebrow>ANSWER</Eyebrow><Body>{card.answer}</Body></Card> : <Action label="Reveal answer" onPress={() => setRevealed(true)} />}{revealed ? <View style={featureStyles.row}>{([1, 2, 3, 4] as const).map((rating) => <Chip key={rating} label={['Again', 'Hard', 'Good', 'Easy'][rating - 1]} onPress={() => void rate(rating)} />)}</View> : null}</Card> : <Card tone="success"><Heading>You are caught up</Heading><Muted>No active-recall cards are due right now.</Muted></Card>}<Message value={message} /></FeatureScreen>;
}

export function FormulaSprintScreen(): React.JSX.Element {
    const [items, setItems] = useState<FormulaItem[]>([]); const [index, setIndex] = useState(0); const [seconds, setSeconds] = useState(300); const [running, setRunning] = useState(false); const [revealed, setRevealed] = useState(false); const [correct, setCorrect] = useState(0); const [title, setTitle] = useState(''); const [expression, setExpression] = useState(''); const [message, run] = useMessage();
    const load = useCallback(async () => setItems((await getFormulas()).items), []); useEffect(() => { void load(); }, [load]);
    useEffect(() => { if (!running || seconds <= 0) return; const timer = setInterval(() => setSeconds((value) => Math.max(0, value - 1)), 1000); return () => clearInterval(timer); }, [running, seconds]);
    useEffect(() => { if (running && seconds === 0) { setRunning(false); void run(createRecallDrillAttempt({ sourceType: 'FORMULA', itemCount: items.length, durationSec: 300, correct, revealed: index }), `Sprint complete: ${correct}/${items.length} correct.`); } }, [correct, index, items.length, run, running, seconds]);
    const answer = (gotIt: boolean): void => { const next = correct + (gotIt ? 1 : 0); setCorrect(next); if (index >= items.length - 1) { setRunning(false); void run(createRecallDrillAttempt({ sourceType: 'FORMULA', itemCount: items.length, durationSec: 300 - seconds, correct: next, revealed: items.length }), `Sprint complete: ${next}/${items.length} correct.`); } else { setIndex((value) => value + 1); setRevealed(false); } };
    const current = items[index];
    return <FeatureScreen title="5-minute Formula Sprint" subtitle="Recall first, reveal second, rate honestly."><Card><Heading>Add formula</Heading><TextInput style={featureStyles.input} value={title} onChangeText={setTitle} placeholder="Formula title" /><TextInput style={featureStyles.input} value={expression} onChangeText={setExpression} placeholder="Expression or rule" /><Action label="Save formula" disabled={!title.trim() || !expression.trim()} onPress={() => void run(createFormula({ title: title.trim(), expression: expression.trim() }).then(load), 'Formula saved.')} /></Card>{!running ? <Card tone="brand"><Heading>{items.length} formulas ready</Heading><Action label="Start 5-minute sprint" disabled={!items.length} onPress={() => { setIndex(0); setCorrect(0); setSeconds(300); setRevealed(false); setRunning(true); }} /></Card> : current ? <Card tone="brand"><View style={featureStyles.between}><Eyebrow>FORMULA {index + 1} OF {items.length}</Eyebrow><Text style={styles.timer}>{Math.floor(seconds / 60)}:{String(seconds % 60).padStart(2, '0')}</Text></View><Text style={styles.prompt}>{current.title}</Text>{revealed ? <Card><Eyebrow>ANSWER</Eyebrow><Body>{current.expression}</Body></Card> : <Action label="Reveal expression" onPress={() => setRevealed(true)} />}{revealed ? <View style={featureStyles.row}><Action label="Got it" onPress={() => answer(true)} /><Action label="Needs review" secondary onPress={() => answer(false)} /></View> : null}</Card> : null}<Message value={message} /></FeatureScreen>;
}

export function ConceptMapBuilderScreen(): React.JSX.Element {
    const [maps, setMaps] = useState<ConceptMap[]>([]); const [title, setTitle] = useState(''); const [nodes, setNodes] = useState(''); const [relations, setRelations] = useState(''); const [message, run] = useMessage();
    const load = useCallback(async () => setMaps((await getConceptMaps()).maps), []); useEffect(() => { void load(); }, [load]);
    const nodeItems = useMemo(() => nodes.split(',').map((value) => value.trim()).filter(Boolean), [nodes]); const edgeItems = useMemo(() => relations.split(',').map((value) => value.split('->').map((part) => part.trim())).filter(([from, to]) => from && to), [relations]);
    const save = async (): Promise<void> => { await run(createConceptMap({ title: title.trim(), nodes: nodeItems.map((label) => ({ id: label.toLowerCase().replace(/\s+/g, '-'), label })), edges: edgeItems.map(([from, to]) => ({ from, to, label: 'relates to' })) }).then(load), 'Concept map saved.'); };
    return <FeatureScreen title="Concept map builder" subtitle="Add concepts, label relationships and keep the map linked to revision."><Card><TextInput style={featureStyles.input} value={title} onChangeText={setTitle} placeholder="Map title" /><TextInput style={featureStyles.input} value={nodes} onChangeText={setNodes} placeholder="Concepts, comma separated" /><TextInput style={featureStyles.input} value={relations} onChangeText={setRelations} placeholder="Relations, e.g. Rights->Remedies" /><View style={styles.map}>{nodeItems.map((node) => <Chip key={node} label={node} selected />)}{edgeItems.map(([from, to], index) => <Body key={`${index}-${from}`}>{from} → {to}</Body>)}</View><View style={featureStyles.row}><Action label="Save concept map" disabled={!title.trim() || nodeItems.length < 2} onPress={() => void save()} /><Action label="Export" secondary disabled={!nodeItems.length} onPress={() => void Share.share({ title: title || 'Concept map', message: `${title}\n${nodeItems.join(' • ')}\n${edgeItems.map(([a, b]) => `${a} → ${b}`).join('\n')}` })} /></View></Card>{maps.slice(0, 4).map((map) => <Card key={map.id} tone="revision"><Heading>{map.title}</Heading><Muted>{Array.isArray(map.nodes) ? map.nodes.length : 0} concepts • {Array.isArray(map.edges) ? map.edges.length : 0} relationships</Muted></Card>)}<Message value={message} /></FeatureScreen>;
}

export function PracticeLabScreen(): React.JSX.Element {
    const [questions, setQuestions] = useState('10'); const [target, setTarget] = useState('600'); const [remaining, setRemaining] = useState(0); const [answered, setAnswered] = useState(0); const [correct, setCorrect] = useState(0); const [skipped, setSkipped] = useState(0); const [simulation, setSimulation] = useState<string[]>([]); const [message, run] = useMessage();
    useEffect(() => { if (remaining <= 0) return; const timer = setInterval(() => setRemaining((value) => Math.max(0, value - 1)), 1000); return () => clearInterval(timer); }, [remaining]);
    const finish = async (nextCorrect = correct, nextSkipped = skipped): Promise<void> => { const count = Math.max(1, Number(questions)); await run(savePacing({ questionCount: count, targetSeconds: Number(target), actualSeconds: Number(target) - remaining, correct: nextCorrect, skipped: nextSkipped }), 'Pacing round saved.'); setRemaining(0); };
    const record = (kind: 'correct' | 'skip'): void => { const nextAnswered = answered + 1; const nextCorrect = correct + (kind === 'correct' ? 1 : 0); const nextSkipped = skipped + (kind === 'skip' ? 1 : 0); setAnswered(nextAnswered); setCorrect(nextCorrect); setSkipped(nextSkipped); if (nextAnswered >= Number(questions)) void finish(nextCorrect, nextSkipped); };
    return <FeatureScreen title="Practice lab" subtitle="Train speed, decisions and answer structure."><Card tone="brand"><View style={featureStyles.between}><Heading>Live pacing</Heading><Text style={styles.timer}>{Math.floor(remaining / 60)}:{String(remaining % 60).padStart(2, '0')}</Text></View>{remaining ? <><Eyebrow>QUESTION {Math.min(answered + 1, Number(questions))} OF {questions}</Eyebrow><Body>Read → decide → answer or skip.</Body><View style={featureStyles.row}><Action label="Correct / next" onPress={() => record('correct')} /><Action label="Skip / next" secondary onPress={() => record('skip')} /></View></> : <><TextInput style={featureStyles.input} value={questions} onChangeText={setQuestions} keyboardType="number-pad" placeholder="Questions" /><TextInput style={featureStyles.input} value={target} onChangeText={setTarget} keyboardType="number-pad" placeholder="Total seconds" /><Action label="Start live pacing" onPress={() => { setAnswered(0); setCorrect(0); setSkipped(0); setRemaining(Math.max(30, Number(target))); }} /></>}</Card><Card><Heading>Strategy simulator</Heading><Action label="Simulate this attempt" onPress={() => void run(simulateStrategy({ questionCount: Number(questions), totalTimeSec: Number(target), targetAttempted: Math.max(1, Number(questions) - 2) }).then(({ simulation: result }) => setSimulation(result.advice)), 'Strategy calculated.')} />{simulation.map((item) => <Body key={item}>• {item}</Body>)}</Card><Message value={message} /></FeatureScreen>;
}

export function AnswerWritingCanvasScreen(): React.JSX.Element {
    const [prompt, setPrompt] = useState(''); const [answer, setAnswer] = useState(''); const [seconds, setSeconds] = useState(600); const [running, setRunning] = useState(false); const [review, setReview] = useState<AnswerWritingAttempt | null>(null); const [selfReview, setSelfReview] = useState<Record<string, boolean>>({}); const [message, run] = useMessage(); const wordCount = answer.trim() ? answer.trim().split(/\s+/).length : 0;
    useEffect(() => { if (!running || seconds <= 0) return; const timer = setInterval(() => setSeconds((value) => Math.max(0, value - 1)), 1000); return () => clearInterval(timer); }, [running, seconds]);
    const submit = async (): Promise<void> => { await run(submitAnswerWriting({ prompt, answerText: answer, timeTakenSec: 600 - seconds }).then(({ attempt }) => setReview(attempt)), 'Saved to your Answer Journal. Review the structure below before your next answer.'); setRunning(false); };
    const checklist = ['Directive addressed', 'Introduction clear', 'Multiple dimensions covered', 'Examples or data used', 'Conclusion present'];
    return <FeatureScreen title="UPSC answer writing" subtitle="10 marks • 150 words • 10 minutes"><Card><TextInput style={featureStyles.input} value={prompt} onChangeText={setPrompt} placeholder="Question or directive" /><View style={featureStyles.between}><Text style={styles.timer}>{Math.floor(seconds / 60)}:{String(seconds % 60).padStart(2, '0')} left</Text><Muted>{wordCount} / 150 words</Muted></View><TextInput style={[featureStyles.input, featureStyles.multiline, styles.answerInput]} value={answer} onChangeText={setAnswer} multiline placeholder="Write introduction, body and conclusion…" />{!running ? <Action label="Start 10-minute answer" disabled={!prompt.trim()} onPress={() => { setSeconds(600); setRunning(true); setSelfReview({}); }} /> : <Action label="Save to Answer Journal" disabled={!answer.trim()} onPress={() => void submit()} />}</Card>{review ? <><Card tone="revision"><Eyebrow>SELF-REVIEW</Eyebrow><Heading>Check the structure before reading feedback</Heading>{checklist.map((item) => <Pressable key={item} style={styles.checkItem} onPress={() => setSelfReview((value) => ({ ...value, [item]: !value[item] }))}><Text style={styles.checkText}>{selfReview[item] ? '✓' : '○'} {item}</Text></Pressable>)}</Card><Card tone="success"><Eyebrow>{review.feedback.source} REVIEW</Eyebrow><Text style={featureStyles.score}>{review.feedback.score}/100</Text><Body>{review.feedback.demandAnalysis}</Body>{Object.entries(review.feedback.criteria).map(([label, value]) => <View key={label}><View style={featureStyles.between}><Muted>{label}</Muted><Muted>{value}/20</Muted></View><Progress value={value * 5} /></View>)}</Card></> : null}<Message value={message} /></FeatureScreen>;
}

export function WellbeingProtocolScreen(): React.JSX.Element {
    const [insights, setInsights] = useState<WellbeingInsights | null>(null); const [checklist, setChecklist] = useState<ChecklistItem[]>([]); const [message, run] = useMessage(); const load = useCallback(async () => { const [wellbeing, list] = await Promise.all([getWellbeingInsights(), getExamChecklist()]); setInsights(wellbeing); setChecklist(list.items); }, []); useEffect(() => { void load(); }, [load]);
    return <FeatureScreen title="Wellbeing protocol" subtitle="Support that adjusts the plan—not your worth."><Card tone={insights?.risk === 'HIGH' ? 'warning' : 'brand'}><Eyebrow>ROLLING LOAD SIGNAL</Eyebrow><Heading>{insights ? `${insights.risk} burnout risk` : 'Reading your recent load…'}</Heading>{insights ? <Body>Average energy {insights.signals.averageEnergy.toFixed(1)} • stress {insights.signals.averageStress.toFixed(1)} • {insights.signals.heavyStudyDays} heavy days</Body> : <ActivityIndicator color={palette.brand} />}<Action label="Apply 3-day recovery plan" onPress={() => void run(createRecoveryPlan('Rolling-load recovery requested from wellbeing screen').then(load), 'Recovery blocks added to your timetable.')} /></Card><Card><Heading>Need relief right now?</Heading><View style={featureStyles.row}><Action label="Box breathing • 2 min" secondary onPress={() => void run(logAnxietyProtocol('BOX_BREATHING', 120), 'Two-minute breathing completed.')} /><Action label="5-4-3-2-1 • 3 min" secondary onPress={() => void run(logAnxietyProtocol('GROUNDING_5_4_3_2_1', 180), 'Grounding completed.')} /></View></Card><Card><Heading>Exam-day checklist</Heading>{checklist.map((item) => <Action key={item.id} label={`${item.completed ? '✓' : '○'} ${item.label}`} secondary onPress={() => void run(updateExamChecklist(item.id, !item.completed).then(load), 'Checklist updated.')} />)}</Card><Message value={message} /></FeatureScreen>;
}

export function GuidanceDoubtsScreen(): React.JSX.Element {
    const [doubts, setDoubts] = useState<DoubtItem[]>([]); const [title, setTitle] = useState(''); const [question, setQuestion] = useState(''); const [tags, setTags] = useState(''); const [url, setUrl] = useState(''); const [role, setRole] = useState<string | null>(null); const [message, run] = useMessage(); const load = useCallback(async () => setDoubts((await getDoubts()).doubts), []); useEffect(() => { void load(); }, [load]);
    return <FeatureScreen title="Guidance & doubts" subtitle="Capture uncertainty, then turn it into action."><Card tone="revision"><Eyebrow>SUGGESTED EXPLORATION</Eyebrow><Heading>{role ?? 'Role-fit guidance is ready when you are'}</Heading><Muted>Heuristic guidance—not a guarantee.</Muted><Action label="Suggest a role fit" secondary onPress={() => void run(Promise.all([getCounselling(), predictRoleFit({ interests: ['analysis', 'administration'] })]).then(([, result]) => setRole(String((result.predictions[0] as Record<string, unknown> | undefined)?.name ?? 'Explore official role descriptions'))), 'Role guidance refreshed.')} /></Card><Card><Heading>Log a doubt</Heading><TextInput style={featureStyles.input} value={title} onChangeText={setTitle} placeholder="Doubt title" /><TextInput style={[featureStyles.input, featureStyles.multiline]} value={question} onChangeText={setQuestion} multiline placeholder="What is unclear?" /><TextInput style={featureStyles.input} value={tags} onChangeText={setTags} placeholder="Tags, comma separated" /><TextInput style={featureStyles.input} value={url} onChangeText={setUrl} placeholder="YouTube/article URL" autoCapitalize="none" /><Action label="Save doubt" disabled={!title.trim() || !question.trim()} onPress={() => void run(createDoubt({ title, question, tags: tags.split(',').map((x) => x.trim()).filter(Boolean), resourceUrls: url ? [url] : [] }).then(load), 'Doubt saved.')} /><Action label="Export CSV" secondary onPress={() => void run(exportDoubtsCsv().then((csv) => Share.share({ title: 'Padhai Karo doubts', message: csv })), 'CSV ready to share.')} /></Card>{doubts.slice(0, 5).map((item) => <Card key={item.id}><Heading>{item.title}</Heading><Muted>{item.status} • {item.tags.join(', ')}</Muted>{item.resourceUrls.map((link) => <Text key={link} style={featureStyles.link} onPress={() => void Linking.openURL(link)}>Open linked resource →</Text>)}</Card>)}<Card><Heading>Coaching sync</Heading><Muted>Connect provider metadata without exposing your login credentials.</Muted><Action label="Connect safely" secondary onPress={() => void run(connectCoaching('MANUAL_PROVIDER'), 'Coaching connection saved.')} /></Card><Message value={message} /></FeatureScreen>;
}

const styles = StyleSheet.create({ prompt: { color: palette.ink, fontSize: 18, lineHeight: 25, fontWeight: '800', marginVertical: 12 }, timer: { color: palette.brandText, fontSize: 18, fontWeight: '800' }, map: { minHeight: 150, borderWidth: 1, borderColor: palette.border, borderRadius: 16, padding: 14, gap: 10, marginTop: 4 }, answerInput: { minHeight: 260 }, checkItem: { borderTopWidth: 1, borderTopColor: palette.border, paddingVertical: 10 }, checkText: { color: palette.ink, fontWeight: '700' } });
