/**
 * EN/HI localized string catalog (Req 10).
 *
 * COPIED FROM: backend/src/lib/localization/catalog.ts (verbatim).
 * See ./types.ts for the copy rationale. Keep in sync with the backend copy.
 *
 * Every entry carries an English (`en`) value; `hi` is provided where a translation exists.
 * A handful of keys deliberately omit `hi` to exercise the English fallback path required by
 * Req 10.3 (see `paywall.restorePurchase` and `common.retry`).
 */

import type { LocalizedString, StringCatalog } from './types';

/**
 * The shipped string catalog. Declared `as const` so each value's key is preserved in the
 * type, letting `StringKey` enumerate the exact set of known keys for callers.
 */
export const stringCatalog = {
    // ── Common actions ────────────────────────────────────────────────────────────────
    'common.save': { en: 'Save', hi: 'सहेजें' },
    'common.cancel': { en: 'Cancel', hi: 'रद्द करें' },
    'common.delete': { en: 'Delete', hi: 'हटाएं' },
    'common.edit': { en: 'Edit', hi: 'संपादित करें' },
    'common.next': { en: 'Next', hi: 'अगला' },
    'common.back': { en: 'Back', hi: 'पीछे' },
    'common.done': { en: 'Done', hi: 'पूर्ण' },
    'common.loading': { en: 'Loading…', hi: 'लोड हो रहा है…' },
    // Intentionally missing `hi` — exercises the English fallback (Req 10.3).
    'common.retry': { en: 'Retry' },

    // ── Onboarding ────────────────────────────────────────────────────────────────────
    'onboarding.title': { en: 'Welcome', hi: 'स्वागत है' },
    'onboarding.selectExam': { en: 'Choose your exam', hi: 'अपनी परीक्षा चुनें' },
    'onboarding.examJee': { en: 'JEE', hi: 'जेईई' },
    'onboarding.examNeet': { en: 'NEET', hi: 'नीट' },
    'onboarding.examUpsc': { en: 'UPSC CSE', hi: 'यूपीएससी सीएसई' },
    'onboarding.examSsc': { en: 'SSC CGL', hi: 'एसएससी सीजीएल' },
    'onboarding.selectStage': { en: 'Choose your stage', hi: 'अपना चरण चुनें' },
    'onboarding.stagePrelims': { en: 'Prelims', hi: 'प्रारंभिक परीक्षा' },
    'onboarding.stageMains': { en: 'Mains', hi: 'मुख्य परीक्षा' },
    'onboarding.stageTier1': { en: 'Tier 1', hi: 'टियर 1' },
    'onboarding.stageTier2': { en: 'Tier 2', hi: 'टियर 2' },
    'onboarding.targetYear': { en: 'Target year', hi: 'लक्ष्य वर्ष' },
    'onboarding.currentClass': { en: 'Current class', hi: 'वर्तमान कक्षा' },
    'onboarding.studyStatus': { en: 'Study status', hi: 'अध्ययन स्थिति' },
    'onboarding.fixedCommitments': { en: 'Fixed commitments', hi: 'निश्चित प्रतिबद्धताएं' },
    'onboarding.peakFocusWindows': { en: 'Peak focus hours', hi: 'सर्वोत्तम एकाग्रता समय' },
    // Client-only onboarding additions (not present in the backend copy) — drive the
    // fixed-commitments editor and the peak-window / weekday labels on the onboarding screen.
    'onboarding.currentClassPlaceholder': { en: 'e.g. Class 12', hi: 'उदा. कक्षा 12' },
    'onboarding.studyStatusPlaceholder': {
        en: 'e.g. College student / Working professional',
        hi: 'उदा. कॉलेज छात्र / नौकरीपेशा',
    },
    'onboarding.fixedCommitmentsCaption': {
        en: 'Optional — add recurring blocks when you cannot study (school, coaching, sleep).',
        hi: 'वैकल्पिक — वे नियमित समय जोड़ें जब आप अध्ययन नहीं कर सकते (स्कूल, कोचिंग, नींद)।',
    },
    'onboarding.peakFocusWindowsCaption': {
        en: 'Optional — pick the times you focus best.',
        hi: 'वैकल्पिक — वे समय चुनें जब आपकी एकाग्रता सर्वोत्तम होती है।',
    },
    'onboarding.commitmentLabel': { en: 'Label', hi: 'नाम' },
    'onboarding.commitmentLabelPlaceholder': { en: 'e.g. School', hi: 'उदा. स्कूल' },
    'onboarding.commitmentStart': { en: 'Start (HH:mm)', hi: 'आरंभ (HH:mm)' },
    'onboarding.commitmentEnd': { en: 'End (HH:mm)', hi: 'समाप्ति (HH:mm)' },
    'onboarding.commitmentDay': { en: 'Day', hi: 'दिन' },
    'onboarding.addCommitment': { en: 'Add commitment', hi: 'प्रतिबद्धता जोड़ें' },
    'onboarding.remove': { en: 'Remove', hi: 'हटाएं' },
    'onboarding.saveError': {
        en: 'Could not save. Please try again.',
        hi: 'सहेजा नहीं जा सका। कृपया पुनः प्रयास करें।',
    },
    'onboarding.peakMorning': { en: 'Morning', hi: 'सुबह' },
    'onboarding.peakAfternoon': { en: 'Afternoon', hi: 'दोपहर' },
    'onboarding.peakNight': { en: 'Night', hi: 'रात' },
    'onboarding.day.sun': { en: 'Sun', hi: 'रवि' },
    'onboarding.day.mon': { en: 'Mon', hi: 'सोम' },
    'onboarding.day.tue': { en: 'Tue', hi: 'मंगल' },
    'onboarding.day.wed': { en: 'Wed', hi: 'बुध' },
    'onboarding.day.thu': { en: 'Thu', hi: 'गुरु' },
    'onboarding.day.fri': { en: 'Fri', hi: 'शुक्र' },
    'onboarding.day.sat': { en: 'Sat', hi: 'शनि' },
    'onboarding.sleepSchedule': { en: 'Sleep schedule', hi: 'नींद का समय', ta: 'தூக்க அட்டவணை', bn: 'ঘুমের সময়সূচি', te: 'నిద్ర షెడ్యూల్', mr: 'झोपेचे वेळापत्रक' },
    'onboarding.sleepScheduleCaption': { en: 'The planner protects wind-down time. Use 24-hour HH:mm.', hi: 'प्लानर आराम के समय की रक्षा करता है। 24-घंटे का HH:mm प्रारूप उपयोग करें।', ta: 'திட்டமிடல் ஓய்வு நேரத்தைப் பாதுகாக்கும். 24 மணி HH:mm வடிவைப் பயன்படுத்தவும்.', bn: 'প্ল্যানার বিশ্রামের সময় রক্ষা করে। ২৪-ঘণ্টার HH:mm ব্যবহার করুন।', te: 'ప్లానర్ విశ్రాంతి సమయాన్ని కాపాడుతుంది. 24-గంటల HH:mm ఉపయోగించండి.', mr: 'प्लॅनर शांत होण्याचा वेळ जपतो. 24-तासांचा HH:mm वापरा.' },
    'onboarding.bedtimePlaceholder': { en: 'Bedtime e.g. 23:00', hi: 'सोने का समय, जैसे 23:00', ta: 'தூங்கும் நேரம், எ.கா. 23:00', bn: 'ঘুমানোর সময়, যেমন ২৩:০০', te: 'నిద్ర సమయం, ఉదా. 23:00', mr: 'झोपेची वेळ, उदा. 23:00' },
    'onboarding.wakeTimePlaceholder': { en: 'Wake time e.g. 07:00', hi: 'जागने का समय, जैसे 07:00', ta: 'எழும் நேரம், எ.கா. 07:00', bn: 'জাগার সময়, যেমন ০৭:০০', te: 'మేల్కొనే సమయం, ఉదా. 07:00', mr: 'उठण्याची वेळ, उदा. 07:00' },
    'onboarding.exactExamDate': { en: 'Exact exam date', hi: 'सटीक परीक्षा तिथि', ta: 'சரியான தேர்வு தேதி', bn: 'সঠিক পরীক্ষার তারিখ', te: 'ఖచ్చితమైన పరీక్ష తేదీ', mr: 'अचूक परीक्षा तारीख' },
    'onboarding.exactExamDateCaption': { en: 'Required for the reverse countdown and automatic revision phases. Use YYYY-MM-DD.', hi: 'रिवर्स काउंटडाउन और स्वचालित पुनरावृत्ति चरणों के लिए आवश्यक। YYYY-MM-DD उपयोग करें।', ta: 'பின்நோக்கு கவுண்ட்டவுன் மற்றும் தானியங்கி மறுபரிசீலனை கட்டங்களுக்கு தேவை. YYYY-MM-DD பயன்படுத்தவும்.', bn: 'রিভার্স কাউন্টডাউন ও স্বয়ংক্রিয় রিভিশন ধাপের জন্য প্রয়োজন। YYYY-MM-DD ব্যবহার করুন।', te: 'రివర్స్ కౌంట్‌డౌన్ మరియు ఆటోమేటిక్ రివిజన్ దశలకు అవసరం. YYYY-MM-DD ఉపయోగించండి.', mr: 'रिव्हर्स काउंटडाउन आणि स्वयंचलित पुनरावृत्ती टप्प्यांसाठी आवश्यक. YYYY-MM-DD वापरा.' },
    'onboarding.examDatePlaceholder': { en: 'e.g. 2027-06-01', hi: 'जैसे 2027-06-01', ta: 'எ.கா. 2027-06-01', bn: 'যেমন ২০২৭-০৬-০১', te: 'ఉదా. 2027-06-01', mr: 'उदा. 2027-06-01' },

    // ── Timetable ─────────────────────────────────────────────────────────────────────
    'timetable.title': { en: 'Timetable', hi: 'समय सारिणी', ta: 'நேர அட்டவணை', bn: 'সময়সূচি', te: 'సమయ పట్టిక', mr: 'वेळापत्रक' },
    'timetable.generate': { en: 'Generate timetable', hi: 'समय सारिणी बनाएं' },
    'timetable.bufferSlot': { en: 'Buffer slot', hi: 'बफर स्लॉट' },
    'timetable.markMissed': { en: 'Mark as missed', hi: 'छूटा हुआ चिह्नित करें' },
    'timetable.overlapError': {
        en: 'This block overlaps another block or a fixed commitment.',
        hi: 'यह ब्लॉक किसी अन्य ब्लॉक या निश्चित प्रतिबद्धता से टकराता है।',
    },
    'timetable.empty': {
        en: 'No blocks for this week. Generate a timetable to begin.',
        hi: 'इस सप्ताह के लिए कोई ब्लॉक नहीं। शुरू करने के लिए समय सारिणी बनाएं।',
    },
    'timetable.subject': { en: 'Subject', hi: 'विषय' },
    'timetable.highEnergy': { en: 'High energy', hi: 'उच्च ऊर्जा' },
    'timetable.lowEnergy': { en: 'Low energy', hi: 'कम ऊर्जा' },
    'timetable.outsidePeak': {
        en: 'Scheduled outside peak focus',
        hi: 'सर्वोत्तम एकाग्रता समय के बाहर निर्धारित',
    },
    // Buffer policy (Req 15.4)
    'timetable.bufferPolicy': { en: 'Unused buffer converts to', hi: 'अप्रयुक्त बफर बदलेगा' },
    'timetable.bufferPolicy.catchUp': { en: 'Catch-up', hi: 'कैच-अप' },
    'timetable.bufferPolicy.extraRevision': { en: 'Extra revision', hi: 'अतिरिक्त पुनरावृत्ति' },
    'timetable.bufferPolicyError': {
        en: 'Could not update the buffer policy.',
        hi: 'बफर नीति अपडेट नहीं हो सकी।',
    },
    // Calendar events (Req 16.1)
    'timetable.addEvent': { en: 'Add event', hi: 'इवेंट जोड़ें' },
    'timetable.event.type': { en: 'Type', hi: 'प्रकार' },
    'timetable.event.startDate': { en: 'Start date', hi: 'आरंभ तिथि' },
    'timetable.event.endDate': { en: 'End date', hi: 'समाप्ति तिथि' },
    'timetable.event.schoolExam': { en: 'School exam', hi: 'स्कूल परीक्षा' },
    'timetable.event.holiday': { en: 'Holiday', hi: 'छुट्टी' },
    'timetable.event.mockTest': { en: 'Mock test', hi: 'मॉक टेस्ट' },
    'timetable.event.dateFormatError': {
        en: 'Enter dates as YYYY-MM-DD.',
        hi: 'तिथियां YYYY-MM-DD के रूप में दर्ज करें।',
    },
    // Holiday sprint offer (Req 16.6)
    'timetable.holidaySprint.title': {
        en: 'Holiday study sprint available',
        hi: 'छुट्टी अध्ययन स्प्रिंट उपलब्ध',
    },
    'timetable.holidaySprint.summary': {
        en: 'A holiday is coming up. Intensify your plan for these days.',
        hi: 'छुट्टी आने वाली है। इन दिनों के लिए अपनी योजना तेज़ करें।',
    },
    'timetable.holidaySprint.suggestedDaily': {
        en: 'Suggested daily study',
        hi: 'सुझाया गया दैनिक अध्ययन',
    },
    'timetable.holidaySprint.hours': { en: 'hours/day', hi: 'घंटे/दिन' },
    'timetable.startTime': { en: 'Start time (ISO)', hi: 'आरंभ समय (ISO)' },
    'timetable.durationMin': { en: 'Duration (minutes)', hi: 'अवधि (मिनट)' },
    'timetable.subjectId': { en: 'Subject id', hi: 'विषय आईडी' },

    // ── Focus timer ───────────────────────────────────────────────────────────────────
    'focus.title': { en: 'Focus timer', hi: 'एकाग्रता टाइमर', ta: 'கவன நேர்காட்டி', bn: 'ফোকাস টাইমার', te: 'ఫోకస్ టైమర్', mr: 'फोकस टाइमर' },
    'focus.start': { en: 'Start', hi: 'शुरू करें' },
    'focus.pause': { en: 'Pause', hi: 'रोकें' },
    'focus.stop': { en: 'Stop', hi: 'समाप्त करें' },
    'focus.selectSubject': { en: 'Select a subject to begin', hi: 'शुरू करने के लिए विषय चुनें' },
    'focus.sessionType.newChapter': { en: 'New chapter', hi: 'नया अध्याय' },
    'focus.sessionType.practiceProblems': { en: 'Practice problems', hi: 'अभ्यास प्रश्न' },
    'focus.sessionType.revision': { en: 'Revision', hi: 'पुनरावृत्ति' },
    'focus.focusedMinutes': { en: 'focused min', hi: 'एकाग्र मिनट', ta: 'கவன நிமிடங்கள்', bn: 'ফোকাস মিনিট', te: 'ఫోకస్ నిమిషాలు', mr: 'फोकस मिनिटे' },
    'focus.sessionType': { en: 'Session type', hi: 'सत्र का प्रकार', ta: 'அமர்வு வகை', bn: 'সেশনের ধরন', te: 'సెషన్ రకం', mr: 'सत्राचा प्रकार' },
    'focus.savedOffline': { en: 'Saved offline — it will sync when you reconnect.', hi: 'ऑफलाइन सहेजा गया — कनेक्शन लौटने पर सिंक होगा।', ta: 'ஆஃப்லைனில் சேமிக்கப்பட்டது — இணைப்பு வந்ததும் ஒத்திசைக்கப்படும்.', bn: 'অফলাইনে সংরক্ষিত — সংযোগ ফিরলে সিঙ্ক হবে।', te: 'ఆఫ్‌లైన్‌లో సేవ్ చేయబడింది — కనెక్షన్ వచ్చినప్పుడు సింక్ అవుతుంది.', mr: 'ऑफलाइन जतन केले — पुन्हा जोडल्यावर सिंक होईल.' },
    'focus.sessionAbandoned': { en: 'Session marked as abandoned; your recovery-aware plan will use this signal.', hi: 'सत्र अधूरा चिह्नित है; आपकी रिकवरी-आधारित योजना इस संकेत का उपयोग करेगी।', ta: 'அமர்வு கைவிடப்பட்டதாகக் குறிக்கப்பட்டது; மீட்பு-அறிந்த திட்டம் இதைப் பயன்படுத்தும்.', bn: 'সেশন পরিত্যক্ত হিসেবে চিহ্নিত; রিকভারি-ভিত্তিক পরিকল্পনা এটি ব্যবহার করবে।', te: 'సెషన్ వదిలివేయబడినట్లు గుర్తించబడింది; రికవరీ-ఆధారిత ప్లాన్ దీన్ని ఉపయోగిస్తుంది.', mr: 'सत्र सोडलेले म्हणून नोंदवले; रिकव्हरी-आधारित योजना हा संकेत वापरेल.' },
    'focus.recorded': { en: 'Recorded.', hi: 'रिकॉर्ड किया गया।', ta: 'பதிவு செய்யப்பட்டது.', bn: 'রেকর্ড করা হয়েছে।', te: 'రికార్డ్ చేయబడింది.', mr: 'नोंदवले.' },
    'focus.loadSubjectsError': { en: 'Could not load subjects.', hi: 'विषय लोड नहीं हो सके।', ta: 'பாடங்களை ஏற்ற முடியவில்லை.', bn: 'বিষয় লোড করা যায়নি।', te: 'విషయాలను లోడ్ చేయలేకపోయాం.', mr: 'विषय लोड करता आले नाहीत.' },
    'focus.recordError': { en: 'Could not record the session.', hi: 'सत्र रिकॉर्ड नहीं हो सका।', ta: 'அமர்வைப் பதிவு செய்ய முடியவில்லை.', bn: 'সেশন রেকોર્ડ করা যায়নি।', te: 'సెషన్‌ను రికార్డ్ చేయలేకపోయాం.', mr: 'सत्र नोंदवता आले नाही.' },

    // ── Progress dashboard ──────────────────────────────────────────────────────────────
    'dashboard.title': { en: 'Progress', hi: 'प्रगति', ta: 'முன்னேற்றம்', bn: 'অগ্রগতি', te: 'పురోగతి', mr: 'प्रगती' },
    'dashboard.streak': { en: 'Streak', hi: 'निरंतरता' },
    'dashboard.studyTimeToday': { en: "Today's study time", hi: 'आज का अध्ययन समय' },
    'dashboard.studyTimeWeek': { en: "This week's study time", hi: 'इस सप्ताह का अध्ययन समय' },
    'dashboard.syllabusCompletion': { en: 'Syllabus completion', hi: 'पाठ्यक्रम पूर्णता' },

    // ── PYQ practice ──────────────────────────────────────────────────────────────────
    'pyq.title': { en: 'Previous year questions', hi: 'पिछले वर्ष के प्रश्न', ta: 'முந்தைய ஆண்டு கேள்விகள்', bn: 'আগের বছরের প্রশ্ন', te: 'గత సంవత్సర ప్రశ్నలు', mr: 'मागील वर्षांचे प्रश्न' },
    'pyq.filterByYear': { en: 'Filter by year', hi: 'वर्ष के अनुसार छाँटें' },
    'pyq.filterBySubject': { en: 'Filter by subject', hi: 'विषय के अनुसार छाँटें' },
    'pyq.submit': { en: 'Submit answers', hi: 'उत्तर जमा करें' },
    'pyq.score': { en: 'Score', hi: 'अंक' },

    // ── Mistake journal ─────────────────────────────────────────────────────────────────
    'mistakes.title': { en: 'Mistake journal', hi: 'गलती डायरी' },
    'mistakes.category.silly': { en: 'Silly mistake', hi: 'लापरवाही की गलती' },
    'mistakes.category.conceptGap': { en: 'Concept gap', hi: 'अवधारणा की कमी' },
    'mistakes.category.timePressure': { en: 'Time pressure', hi: 'समय का दबाव' },
    'mistakes.category.neverSeen': { en: 'Never seen this', hi: 'पहले कभी नहीं देखा' },
    'mistakes.addNote': { en: 'Add a note', hi: 'एक टिप्पणी जोड़ें' },

    // ── AI notes summarizer ─────────────────────────────────────────────────────────────
    'ai.title': { en: 'AI notes', hi: 'एआई नोट्स', ta: 'AI குறிப்புகள்', bn: 'AI নোট', te: 'AI నోట్స్', mr: 'AI नोट्स' },
    'ai.summarizeText': { en: 'Summarize text', hi: 'पाठ का सारांश बनाएं' },
    'ai.summarizePhoto': { en: 'Summarize photo', hi: 'फ़ोटो का सारांश बनाएं' },
    'ai.remainingQuota': { en: 'Remaining summaries', hi: 'शेष सारांश' },
    'ai.emptyInputError': {
        en: 'Enter some note text to summarize.',
        hi: 'सारांश बनाने के लिए कुछ नोट्स दर्ज करें।',
    },

    // ── Paywall / subscription ──────────────────────────────────────────────────────────
    'paywall.title': { en: 'Upgrade to Paid', hi: 'पेड में अपग्रेड करें' },
    'paywall.upgradeCta': { en: 'Upgrade now', hi: 'अभी अपग्रेड करें' },
    'paywall.upgradeRequired': {
        en: 'AI notes are a Paid feature. Upgrade to continue.',
        hi: 'एआई नोट्स एक पेड सुविधा है। जारी रखने के लिए अपग्रेड करें।',
    },
    'paywall.quotaExceeded': {
        en: "You've used all your AI summaries for now.",
        hi: 'आपने अभी के लिए अपने सभी एआई सारांश उपयोग कर लिए हैं।',
    },
    // Intentionally missing `hi` — exercises the English fallback (Req 10.3).
    'paywall.restorePurchase': { en: 'Restore purchase' },

    // ── NTA update feed ─────────────────────────────────────────────────────────────────
    'nta.title': { en: 'NTA updates', hi: 'एनटीए अपडेट' },
    'nta.empty': { en: 'No announcements yet.', hi: 'अभी तक कोई घोषणा नहीं।' },
    'nta.examDateChanged': { en: 'Exam date updated', hi: 'परीक्षा तिथि अपडेट हुई' },
    'nta.loadError': {
        en: 'Could not load the NTA feed.',
        hi: 'एनटीए फ़ीड लोड नहीं हो सका।',
    },

    // ── Auth (client-only additions; not present in the backend copy) ───────────────────
    'auth.login': { en: 'Log in', hi: 'लॉग इन करें' },
    'auth.register': { en: 'Create account', hi: 'खाता बनाएं' },
    'auth.email': { en: 'Email', hi: 'ईमेल' },
    'auth.password': { en: 'Password', hi: 'पासवर्ड' },
    'auth.logout': { en: 'Log out', hi: 'लॉग आउट करें' },
    'auth.needAccount': { en: 'Need an account? Create one', hi: 'खाता चाहिए? एक बनाएं' },
    'auth.haveAccount': { en: 'Already have an account? Log in', hi: 'पहले से खाता है? लॉग इन करें' },
    'auth.missingFields': {
        en: 'Enter your email and password.',
        hi: 'अपना ईमेल और पासवर्ड दर्ज करें।',
    },
    'auth.genericError': {
        en: 'Something went wrong. Check your connection and try again.',
        hi: 'कुछ गलत हो गया। अपना कनेक्शन जांचें और पुनः प्रयास करें।',
    },

    // ── Progress dashboard (client-only additions; task 21.5) ───────────────────────────
    'dashboard.loadError': {
        en: 'Could not load your dashboard.',
        hi: 'आपका डैशबोर्ड लोड नहीं हो सका।',
    },
    'dashboard.noSessionsToday': { en: 'No sessions yet today.', hi: 'आज अभी तक कोई सत्र नहीं।' },
    'dashboard.noSessionsWeek': {
        en: 'No sessions yet this week.',
        hi: 'इस सप्ताह अभी तक कोई सत्र नहीं।',
    },
    'dashboard.velocity': { en: 'Velocity', hi: 'गति' },
    'dashboard.velocityStatus': { en: 'Status', hi: 'स्थिति' },
    'dashboard.velocityAhead': { en: 'Ahead', hi: 'आगे' },
    'dashboard.velocityBehind': { en: 'Behind', hi: 'पीछे' },
    'dashboard.targetCompletion': { en: 'Target completion', hi: 'लक्ष्य पूर्णता' },
    'dashboard.projectedCompletion': { en: 'Projected completion', hi: 'अनुमानित पूर्णता' },
    'dashboard.dayDelta': { en: 'Day delta', hi: 'दिनों का अंतर' },
    'dashboard.daysUnit': { en: 'days', hi: 'दिन' },
    'dashboard.chapters': { en: 'Chapters', hi: 'अध्याय' },
    'dashboard.noChapters': { en: 'No chapters yet.', hi: 'अभी तक कोई अध्याय नहीं।' },
    'dashboard.chapterStatusError': {
        en: 'Could not update the chapter. Status only moves forward.',
        hi: 'अध्याय अपडेट नहीं हो सका। स्थिति केवल आगे बढ़ती है।',
    },

    // ── Chapter status labels (client-only additions; task 21.5, Req 12.1) ──────────────
    'chapter.status.notStarted': { en: 'Not started', hi: 'शुरू नहीं हुआ' },
    'chapter.status.inProgress': { en: 'In progress', hi: 'प्रगति में' },
    'chapter.status.done': { en: 'Done', hi: 'पूर्ण' },
    'chapter.status.revised': { en: 'Revised', hi: 'पुनरावलोकित' },

    // ── Daily check-in (client-only additions; task 21.5, Req 14.1) ─────────────────────
    'checkin.title': { en: 'Daily check-in', hi: 'दैनिक चेक-इन' },
    'checkin.hint': {
        en: "Log today's planned study time. Leave actual blank to use your focus sessions.",
        hi: 'आज का नियोजित अध्ययन समय दर्ज करें। फोकस सत्रों का उपयोग करने के लिए वास्तविक खाली छोड़ें।',
    },
    'checkin.plannedLabel': { en: 'Planned minutes', hi: 'नियोजित मिनट' },
    'checkin.actualLabel': { en: 'Actual minutes (optional)', hi: 'वास्तविक मिनट (वैकल्पिक)' },
    'checkin.plannedPlaceholder': { en: 'e.g. 180', hi: 'उदा. 180' },
    'checkin.actualPlaceholder': {
        en: 'Leave blank to use focus sessions',
        hi: 'फोकस सत्र उपयोग करने हेतु खाली छोड़ें',
    },
    'checkin.plannedError': {
        en: 'Enter planned minutes as a whole number (e.g. 180).',
        hi: 'नियोजित मिनट एक पूर्ण संख्या के रूप में दर्ज करें (उदा. 180)।',
    },
    'checkin.actualError': {
        en: 'Actual minutes must be a whole number, or left blank.',
        hi: 'वास्तविक मिनट एक पूर्ण संख्या होनी चाहिए, या खाली छोड़ें।',
    },
    'checkin.saveError': {
        en: 'Could not save your check-in. Please try again.',
        hi: 'आपका चेक-इन सहेजा नहीं जा सका। कृपया पुनः प्रयास करें।',
    },
    'checkin.saved': { en: 'Saved', hi: 'सहेजा गया' },
    'checkin.saveButton': { en: 'Save check-in', hi: 'चेक-इन सहेजें' },

    // ── UPSC/SSC product surfaces ─────────────────────────────────────────────────────
    'planner.title': { en: 'Today’s plan', hi: 'आज की योजना', ta: 'இன்றைய திட்டம்', bn: 'আজকের পরিকল্পনা', te: 'నేటి ప్రణాళిక', mr: 'आजची योजना' },
    'planner.setExamDate': { en: 'Set an exam date', hi: 'परीक्षा तिथि सेट करें', ta: 'தேர்வு தேதியை அமைக்கவும்', bn: 'পরীক্ষার তারিখ সেট করুন', te: 'పరీక్ష తేదీని సెట్ చేయండి', mr: 'परीक्षा तारीख सेट करा' },
    'planner.daysToGo': { en: 'days to go', hi: 'दिन शेष', ta: 'நாட்கள் மீதம்', bn: 'দিন বাকি', te: 'రోజులు మిగిలి ఉన్నాయి', mr: 'दिवस बाकी' },
    'planner.timeDebt': { en: 'Time debt', hi: 'समय ऋण', ta: 'நேரக் கடன்', bn: 'সময়ের ঘাটতি', te: 'సమయ లోటు', mr: 'वेळेची उणीव' },
    'planner.efficiency': { en: 'Efficiency', hi: 'दक्षता', ta: 'செயல்திறன்', bn: 'দক্ষতা', te: 'సామర్థ్యం', mr: 'कार्यक्षमता' },
    'planner.dailyTarget': { en: 'Daily target', hi: 'दैनिक लक्ष्य', ta: 'தினசரி இலக்கு', bn: 'দৈনিক লক্ষ্য', te: 'రోజువారీ లక్ష్యం', mr: 'दैनिक लक्ष्य' },
    'planner.revisionCycle': { en: 'Revision cycle', hi: 'पुनरावृत्ति चक्र', ta: 'மறுபரிசீலனை சுழற்சி', bn: 'পুনরাবৃত্তি চক্র', te: 'పునశ్చరణ చక్రం', mr: 'पुनरावृत्ती चक्र' },
    'planner.examCountdown': { en: 'Exam countdown', hi: 'परीक्षा उलटी गिनती', ta: 'தேர்வு கவுண்ட்டவுன்', bn: 'পরীক্ষার কাউন্টডাউন', te: 'పరీక్ష కౌంట్‌డౌన్', mr: 'परीक्षा उलटी गिनती' },
    'planner.priorityTopics': { en: 'Priority topics', hi: 'प्राथमिकता विषय', ta: 'முன்னுரிமை தலைப்புகள்', bn: 'অগ্রাধিকার বিষয়', te: 'ప్రాధాన్య అంశాలు', mr: 'प्राधान्य विषय' },
    'planner.dailyBriefing': { en: 'Daily briefing', hi: 'दैनिक ब्रीफिंग', ta: 'தினசரி விளக்கம்', bn: 'দৈনিক ব্রিফিং', te: 'రోజువారీ బ్రీఫింగ్', mr: 'दैनिक ब्रीफिंग' },
    'planner.calendar': { en: 'Calendar commitments', hi: 'कैलेंडर प्रतिबद्धताएं', ta: 'காலண்டர் ஒப்பந்தங்கள்', bn: 'ক্যালেন্ডার প্রতিশ্রুতি', te: 'క్యాలెండర్ కట్టుబాట్లు', mr: 'कॅलेंडर बांधिलकी' },
    'planner.refresh': { en: 'Refresh briefing', hi: 'ब्रीफिंग रीफ्रेश करें', ta: 'விளக்கத்தைப் புதுப்பிக்கவும்', bn: 'ব্রিফিং রিফ্রেশ করুন', te: 'బ్రీఫింగ్ రిఫ్రెష్ చేయండి', mr: 'ब्रीफिंग रिफ्रेश करा' },
    'analytics.title': { en: 'Analytics', hi: 'विश्लेषण', ta: 'பகுப்பாய்வு', bn: 'বিশ্লেষণ', te: 'విశ్లేషణ', mr: 'विश्लेषण' },
    'analytics.weakAreas': { en: 'Weak areas', hi: 'कमजोर क्षेत्र', ta: 'பலவீன பகுதிகள்', bn: 'দুর্বল ক্ষেত্র', te: 'బలహీన ప్రాంతాలు', mr: 'कमकुवत क्षेत्रे' },
    'analytics.topicTrends': { en: 'Topic trends', hi: 'विषय रुझान', ta: 'தலைப்பு போக்குகள்', bn: 'বিষয় প্রবণতা', te: 'అంశాల ధోరణులు', mr: 'विषय ट्रेंड्स' },
    'analytics.scoreTrajectory': { en: 'Score trajectory', hi: 'स्कोर प्रगति', ta: 'மதிப்பெண் முன்னேற்றம்', bn: 'স্কোর অগ্রগতি', te: 'స్కోర్ పురోగతి', mr: 'स्कोअर प्रगती' },
    'analytics.benchmark': { en: 'Benchmark', hi: 'बेंचमार्क', ta: 'தரநிலை', bn: 'বেঞ্চমার্ক', te: 'బెంచ్‌మార్క్', mr: 'बेंचमार्क' },
    'analytics.rankPrediction': { en: 'Rank prediction', hi: 'रैंक अनुमान', ta: 'தரவரிசை கணிப்பு', bn: 'র‍্যাঙ্ক পূর্বাভাস', te: 'ర్యాంక్ అంచనా', mr: 'रँक अंदाज' },
    'analytics.retry': { en: 'Retry', hi: 'पुनः प्रयास', ta: 'மீண்டும் முயற்சிக்கவும்', bn: 'আবার চেষ্টা করুন', te: 'మళ్లీ ప్రయత్నించండి', mr: 'पुन्हा प्रयत्न करा' },
    'analytics.refreshAll': { en: 'Refresh all', hi: 'सब रीफ्रेश करें', ta: 'அனைத்தையும் புதுப்பிக்கவும்', bn: 'সব রিফ্রেশ করুন', te: 'అన్నింటినీ రిఫ్రెష్ చేయండి', mr: 'सर्व रीफ्रेश करा' },
    'analytics.intro': { en: 'Your UPSC/SSC signals stay private to your account. Reference benchmarks are anonymised.', hi: 'आपके UPSC/SSC संकेत आपके खाते तक सीमित रहते हैं। संदर्भ बेंचमार्क गुमनाम हैं।', ta: 'உங்கள் UPSC/SSC தரவுகள் உங்கள் கணக்கில் மட்டுமே இருக்கும். ஒப்பீட்டு அளவுகோல்கள் அடையாளமற்றவை.', bn: 'আপনার UPSC/SSC ডেটা আপনার অ্যাকাউন্টেই থাকে। রেফারেন্স বেঞ্চমার্ক পরিচয়হীন।', te: 'మీ UPSC/SSC సిగ్నల్స్ మీ ఖాతాలోనే ఉంటాయి. రిఫరెన్స్ బెంచ్‌మార్క్‌లు అనామకంగా ఉంటాయి.', mr: 'तुमचे UPSC/SSC संकेत तुमच्या खात्यातच राहतात. संदर्भ बेंचमार्क अनामिक आहेत.' },
    'analytics.partialError': { en: 'Some analytics sections could not load. Retry to refresh them.', hi: 'कुछ विश्लेषण भाग लोड नहीं हो सके। उन्हें रीफ्रेश करने के लिए दोबारा प्रयास करें।', ta: 'சில பகுப்பாய்வு பகுதிகளை ஏற்ற முடியவில்லை. புதுப்பிக்க மீண்டும் முயற்சிக்கவும்.', bn: 'কিছু অ্যানালিটিক্স সেকশন লোড হয়নি। রিফ্রেশ করতে আবার চেষ্টা করুন।', te: 'కొన్ని అనలిటిక్స్ విభాగాలు లోడ్ కాలేదు. రిఫ్రెష్ చేయడానికి మళ్లీ ప్రయత్నించండి.', mr: 'काही विश्लेषण विभाग लोड झाले नाहीत. रीफ्रेश करण्यासाठी पुन्हा प्रयत्न करा.' },
    'analytics.review': { en: 'Review', hi: 'समीक्षा करें', ta: 'மதிப்பாய்வு', bn: 'রিভিউ', te: 'రివ్యూ', mr: 'पुनरावलोकन' },
    'analytics.emptyWeak': { en: 'Complete a few practice attempts to see weak areas.', hi: 'कमजोर क्षेत्र देखने के लिए कुछ अभ्यास प्रयास पूरे करें।', ta: 'பலவீன பகுதிகளைப் பார்க்க சில பயிற்சிகளை முடிக்கவும்.', bn: 'দুর্বল ক্ষেত্র দেখতে কয়েকটি প্র্যাকটিস শেষ করুন।', te: 'బలహీన ప్రాంతాలను చూడటానికి కొన్ని ప్రాక్టీస్ ప్రయత్నాలు పూర్తి చేయండి.', mr: 'कमकुवत क्षेत्रे पाहण्यासाठी काही सराव पूर्ण करा.' },
    'analytics.emptyTopics': { en: 'Topic-frequency data is not available yet.', hi: 'विषय-आवृत्ति डेटा अभी उपलब्ध नहीं है।', ta: 'தலைப்பு அதிர்வெண் தரவு இன்னும் இல்லை.', bn: 'বিষয়-ফ্রিকোয়েন্সি ডেটা এখনও নেই।', te: 'టాపిక్ ఫ్రీక్వెన్సీ డేటా ఇంకా అందుబాటులో లేదు.', mr: 'विषय-वार वारंवारता डेटा अजून उपलब्ध नाही.' },
    'analytics.emptyScores': { en: 'No score points recorded yet.', hi: 'अभी कोई स्कोर दर्ज नहीं है।', ta: 'இன்னும் மதிப்பெண் பதிவு இல்லை.', bn: 'এখনও কোনো স্কোর রেকর্ড নেই।', te: 'ఇంకా స్కోర్ పాయింట్లు నమోదు కాలేదు.', mr: 'अजून कोणतेही स्कोअर नोंदलेले नाहीत.' },
    'analytics.noBenchmark': { en: 'Not enough cohort data yet.', hi: 'अभी पर्याप्त समूह डेटा नहीं है।', ta: 'இன்னும் போதுமான குழுத் தரவு இல்லை.', bn: 'এখনও যথেষ্ট কোহর্ট ডেটা নেই।', te: 'ఇంకా తగిన కోహోర్ట్ డేటా లేదు.', mr: 'अजून पुरेसा समूह डेटा नाही.' },
    'analytics.noRank': { en: 'Add mock scores to unlock this view.', hi: 'यह दृश्य खोलने के लिए मॉक स्कोर जोड़ें।', ta: 'இந்தக் காட்சியைத் திறக்க மாக் மதிப்பெண்களைச் சேர்க்கவும்.', bn: 'এই ভিউ আনলক করতে মক স্কোর যোগ করুন।', te: 'ఈ వీక్షణను తెరవడానికి మాక్ స్కోర్‌లను జోడించండి.', mr: 'हे दृश्य उघडण्यासाठी मॉक स्कोअर जोडा.' },
    'analytics.sessionMix': { en: 'Study session mix', hi: 'अध्ययन सत्र मिश्रण', ta: 'படிப்பு அமர்வு கலவை', bn: 'স্টাডি সেশন মিক্স', te: 'స్టడీ సెషన్ మిక్స్', mr: 'अभ्यास सत्र मिश्रण' },
    'analytics.detail': { en: 'Selected insight', hi: 'चयनित जानकारी', ta: 'தேர்ந்தெடுத்த பார்வை', bn: 'নির্বাচিত ইনসাইট', te: 'ఎంచుకున్న ఇన్‌సైట్', mr: 'निवडलेली माहिती' },
    'analytics.attempts': { en: 'Attempts', hi: 'प्रयास', ta: 'முயற்சிகள்', bn: 'প্রচেষ্টা', te: 'ప్రయత్నాలు', mr: 'प्रयत्न' },
    'analytics.percentile': { en: 'Percentile', hi: 'प्रतिशतक', ta: 'சதவீத நிலை', bn: 'পার্সেন্টাইল', te: 'పర్సెంటైల్', mr: 'पर्सेंटाइल' },
    'analytics.cohort': { en: 'Cohort size', hi: 'समूह आकार', ta: 'குழு அளவு', bn: 'কোহর্ট সাইজ', te: 'కోహోర్ట్ పరిమాణం', mr: 'समूह आकार' },
    'analytics.overview': { en: 'Overview', hi: 'सारांश', ta: 'கண்ணோட்டம்', bn: 'ওভারভিউ', te: 'అవలోకనం', mr: 'आढावा' },
    'analytics.scores': { en: 'Scores', hi: 'स्कोर', ta: 'மதிப்பெண்கள்', bn: 'স্কোর', te: 'స్కోర్లు', mr: 'स्कोअर' },
    'analytics.sessions': { en: 'Sessions', hi: 'सत्र', ta: 'அமர்வுகள்', bn: 'সেশন', te: 'సెషన్లు', mr: 'सत्रे' },
    'analytics.last': { en: 'Last', hi: 'पिछले', ta: 'கடந்த', bn: 'গত', te: 'గత', mr: 'मागील' },
    'analytics.scoreRange': { en: 'Score range', hi: 'स्कोर अवधि', ta: 'மதிப்பெண் காலவரம்பு', bn: 'স্কোর সময়সীমা', te: 'స్కోర్ పరిధి', mr: 'स्कोअर कालावधी' },
    'analytics.allTime': { en: 'All time', hi: 'सभी समय', ta: 'முழு காலம்', bn: 'সব সময়', te: 'మొత్తం కాలం', mr: 'सर्व काळ' },
    'analytics.tapToDrillDown': { en: 'Tap any row to inspect the signal behind it.', hi: 'सिग्नल की जानकारी देखने के लिए किसी पंक्ति पर टैप करें।', ta: 'சிக்னலின் விவரங்களைப் பார்க்க எந்த வரியையும் தட்டவும்.', bn: 'সিগন্যালের বিস্তারিত দেখতে যেকোনো সারিতে ট্যাপ করুন।', te: 'సిగ్నల్ వివరాలను చూడటానికి ఏదైనా వరుసను ట్యాప్ చేయండి.', mr: 'सिग्नल तपशील पाहण्यासाठी कोणत्याही रांगेवर टॅप करा.' },
    'analytics.score': { en: 'Score', hi: 'स्कोर', ta: 'மதிப்பெண்', bn: 'স্কোর', te: 'స్కోర్', mr: 'स्कोअर' },
    'analytics.source': { en: 'Source', hi: 'स्रोत', ta: 'மூலம்', bn: 'উৎস', te: 'మూలం', mr: 'स्रोत' },
    'analytics.obtained': { en: 'Obtained', hi: 'प्राप्त', ta: 'பெற்றது', bn: 'প্রাপ্ত', te: 'పొందినది', mr: 'प्राप्त' },
    'analytics.subject': { en: 'Subject', hi: 'विषय', ta: 'பாடம்', bn: 'বিষয়', te: 'విషయం', mr: 'विषय' },
    'analytics.appearances': { en: 'Past appearances', hi: 'पिछली उपस्थिति', ta: 'முந்தைய தோற்றங்கள்', bn: 'পূর্ব উপস্থিতি', te: 'గత ప్రదర్శనలు', mr: 'मागील उपस्थिती' },
    'analytics.averagePerYear': { en: 'Average per year', hi: 'प्रति वर्ष औसत', ta: 'ஆண்டுக்கு சராசரி', bn: 'প্রতি বছর গড়', te: 'సంవత్సరానికి సగటు', mr: 'दरवर्षी सरासरी' },
    'analytics.coverage': { en: 'Coverage', hi: 'कवरेज', ta: 'கவரேஜ்', bn: 'কভারেজ', te: 'కవరేజ్', mr: 'कव्हरेज' },
    'analytics.noFrequency': { en: 'No frequency data', hi: 'आवृत्ति डेटा नहीं', ta: 'அதிர்வெண் தரவு இல்லை', bn: 'ফ্রিকোয়েন্সি ডেটা নেই', te: 'ఫ్రీక్వెన్సీ డేటా లేదు', mr: 'वारंवारता डेटा नाही' },
    'analytics.minutes': { en: 'minutes', hi: 'मिनट', ta: 'நிமிடங்கள்', bn: 'মিনিট', te: 'నిమిషాలు', mr: 'मिनिटे' },
    'analytics.share': { en: 'Share', hi: 'हिस्सा', ta: 'பங்கு', bn: 'অংশ', te: 'వాటా', mr: 'हिस्सा' },
    'analytics.median': { en: 'Median', hi: 'मध्यिका', ta: 'நடு மதிப்பு', bn: 'মধ্যমা', te: 'మధ్య విలువ', mr: 'मध्यिका' },
    'analytics.latestScore': { en: 'Latest score', hi: 'नवीनतम स्कोर', ta: 'சமீபத்திய மதிப்பெண்', bn: 'সাম্প্রতিক স্কোর', te: 'తాజా స్కోర్', mr: 'नवीनतम स्कोअर' },
    'analytics.averageScore': { en: 'Average', hi: 'औसत', ta: 'சராசரி', bn: 'গড়', te: 'సగటు', mr: 'सरासरी' },
    'analytics.bestScore': { en: 'Best score', hi: 'सर्वश्रेष्ठ स्कोर', ta: 'சிறந்த மதிப்பெண்', bn: 'সেরা স্কোর', te: 'ఉత్తమ స్కోర్', mr: 'सर्वोत्तम स्कोअर' },
    'analytics.incorrect': { en: 'Incorrect', hi: 'गलत', ta: 'தவறானவை', bn: 'ভুল', te: 'తప్పులు', mr: 'चुकीचे' },
    'analytics.needMoreScores': { en: 'Need more score points', hi: 'और स्कोर पॉइंट चाहिए', ta: 'மேலும் மதிப்பெண் புள்ளிகள் தேவை', bn: 'আরও স্কোর পয়েন্ট দরকার', te: 'మరిన్ని స్కోర్ పాయింట్లు అవసరం', mr: 'अधिक स्कोअर पॉइंट्स आवश्यक' },
    'planner.aiBriefing': { en: 'AI-generated briefing', hi: 'AI से बना ब्रीफिंग', ta: 'AI உருவாக்கிய விளக்கம்', bn: 'AI-জেনারেটেড ব্রিফিং', te: 'AI రూపొందించిన బ్రీఫింగ్', mr: 'AI-निर्मित ब्रीफिंग' },
    'planner.ruleBriefing': { en: 'Rule-based briefing', hi: 'नियम-आधारित ब्रीफिंग', ta: 'விதி அடிப்படையிலான விளக்கம்', bn: 'নিয়ম-ভিত্তিক ব্রিফিং', te: 'రూల్ ఆధారిత బ్రీఫింగ్', mr: 'नियम-आधारित ब्रीफिंग' },
    'planner.revisionBody': { en: 'cards due today · automatic intervals +1 / +3 / +7 / +21 days.', hi: 'कार्ड आज देय हैं · स्वचालित अंतराल +1 / +3 / +7 / +21 दिन।', ta: 'இன்று நிலுவையில் உள்ள அட்டைகள் · தானியங்கி இடைவெளிகள் +1 / +3 / +7 / +21 நாட்கள்.', bn: 'আজকের কার্ড · স্বয়ংক্রিয় ব্যবধান +1 / +3 / +7 / +21 দিন।', te: 'ఈ రోజు కార్డులు · ఆటోమేటిక్ విరామాలు +1 / +3 / +7 / +21 రోజులు.', mr: 'आज देय कार्ड · स्वयंचलित अंतर +1 / +3 / +7 / +21 दिवस.' },
    'planner.noRevisionSequence': { en: 'Complete a chapter to generate its fixed revision sequence.', hi: 'निश्चित रिवीजन क्रम बनाने के लिए एक अध्याय पूरा करें।', ta: 'நிலையான மறுபரிசீலனை வரிசையை உருவாக்க ஒரு அத்தியாயத்தை முடிக்கவும்.', bn: 'স্থির রিভিশন সিকোয়েন্স তৈরি করতে একটি অধ্যায় শেষ করুন।', te: 'స్థిరమైన రివిజన్ సీక్వెన్స్ కోసం ఒక అధ్యాయాన్ని పూర్తి చేయండి.', mr: 'निश्चित पुनरावृत्ती क्रम तयार करण्यासाठी एक अध्याय पूर्ण करा.' },
    'planner.examCountdownBody': { en: 'Add or update an exact UPSC/SSC exam date to drive phase-aware planning.', hi: 'चरण-आधारित योजना के लिए सटीक UPSC/SSC परीक्षा तिथि जोड़ें या अपडेट करें।', ta: 'கட்ட அடிப்படையிலான திட்டமிடலுக்கு சரியான UPSC/SSC தேர்வு தேதியைச் சேர்க்கவும்.', bn: 'ফেজ-ভিত্তিক পরিকল্পনার জন্য সঠিক UPSC/SSC পরীক্ষার তারিখ যোগ বা আপডেট করুন।', te: 'దశ ఆధారిత ప్లానింగ్ కోసం ఖచ్చితమైన UPSC/SSC పరీక్ష తేదీని జోడించండి.', mr: 'टप्पा-आधारित नियोजनासाठी अचूक UPSC/SSC परीक्षा तारीख जोडा किंवा अपडेट करा.' },
    'planner.examLabel': { en: 'Exam label', hi: 'परीक्षा लेबल', ta: 'தேர்வு பெயர்', bn: 'পরীক্ষার লেবেল', te: 'పరీక్ష లేబుల్', mr: 'परीक्षा लेबल' },
    'planner.saveExamDate': { en: 'Save exam date', hi: 'परीक्षा तिथि सहेजें', ta: 'தேர்வு தேதியைச் சேமிக்கவும்', bn: 'পরীক্ষার তারিখ সংরক্ষণ করুন', te: 'పరీక్ష తేదీని సేవ్ చేయండి', mr: 'परीक्षा तारीख जतन करा' },
    'planner.syllabusClear': { en: 'Your syllabus is clear for now.', hi: 'अभी आपका सिलेबस व्यवस्थित है।', ta: 'இப்போது உங்கள் பாடத்திட்டம் தெளிவாக உள்ளது.', bn: 'এই মুহূর্তে আপনার সিলেবাস পরিষ্কার।', te: 'ప్రస్తుతం మీ సిలబస్ స్పష్టంగా ఉంది.', mr: 'आत्ता तुमचा अभ्यासक्रम व्यवस्थित आहे.' },
    'planner.refreshBriefing': { en: 'Refresh briefing', hi: 'ब्रीफिंग रीफ्रेश करें', ta: 'விளக்கத்தைப் புதுப்பிக்கவும்', bn: 'ব্রিফিং রিফ্রেশ করুন', te: 'బ్రీఫింగ్‌ను రిఫ్రెష్ చేయండి', mr: 'ब्रीफिंग रीफ्रेश करा' },
    'planner.refreshing': { en: 'Refreshing…', hi: 'रीफ्रेश हो रहा है…', ta: 'புதுப்பிக்கிறது…', bn: 'রিফ্রেশ হচ্ছে…', te: 'రిఫ్రెష్ అవుతోంది…', mr: 'रीफ्रेश होत आहे…' },
    'planner.briefingRefreshError': { en: 'Could not refresh the briefing.', hi: 'ब्रीफिंग रीफ्रेश नहीं हो सकी।', ta: 'விளக்கத்தைப் புதுப்பிக்க முடியவில்லை.', bn: 'ব্রিফিং রিফ্রেশ করা যায়নি।', te: 'బ్రీఫింగ్‌ను రిఫ్రెష్ చేయలేకపోయాం.', mr: 'ब्रीफिंग रीफ्रेश करता आली नाही.' },
    'planner.calendarCommitments': { en: 'Calendar commitments', hi: 'कैलेंडर प्रतिबद्धताएं', ta: 'காலண்டர் உறுதிப்பாடுகள்', bn: 'ক্যালেন্ডার কমিটমেন্ট', te: 'క్యాలెండర్ కమిట్‌మెంట్‌లు', mr: 'कॅलेंडर बांधिलकी' },
    'planner.calendarBody': { en: 'Import upcoming Google Calendar events so study time respects mock tests, exams and holidays.', hi: 'आने वाले Google Calendar कार्यक्रम आयात करें ताकि पढ़ाई का समय मॉक टेस्ट, परीक्षा और छुट्टियों का ध्यान रखे।', ta: 'வரும் Google Calendar நிகழ்வுகளை இறக்குமதி செய்து படிப்பு நேரம் தேர்வுகள் மற்றும் விடுமுறைகளை மதிக்கச் செய்யவும்.', bn: 'আসন্ন Google Calendar ইভেন্ট ইমপোর্ট করুন যাতে পড়ার সময় মক টেস্ট, পরীক্ষা ও ছুটি মানে।', te: 'రాబోయే Google Calendar ఈవెంట్‌లను దిగుమతి చేసి స్టడీ సమయం మాక్‌లు, పరీక్షలు, సెలవులను పరిగణనలోకి తీసుకోండి.', mr: 'आगामी Google Calendar कार्यक्रम आयात करा, जेणेकरून अभ्यासाचा वेळ मॉक, परीक्षा आणि सुट्ट्यांचा विचार करेल.' },
    'planner.connected': { en: 'Connected', hi: 'कनेक्टेड', ta: 'இணைக்கப்பட்டது', bn: 'সংযুক্ত', te: 'కనెక్ట్ అయింది', mr: 'कनेक्ट केले' },
    'planner.notConnected': { en: 'Not connected', hi: 'कनेक्ट नहीं है', ta: 'இணைக்கப்படவில்லை', bn: 'সংযুক্ত নয়', te: 'కనెక్ట్ కాలేదు', mr: 'कनेक्ट केलेले नाही' },
    'planner.disconnect': { en: 'Disconnect', hi: 'डिस्कनेक्ट करें', ta: 'துண்டிக்கவும்', bn: 'ডিসকানেক্ট', te: 'డిస్‌కనెక్ట్ చేయండి', mr: 'डिस्कनेक्ट करा' },
    'planner.connectGoogle': { en: 'Connect Google', hi: 'Google कनेक्ट करें', ta: 'Google இணைக்கவும்', bn: 'Google সংযোগ করুন', te: 'Googleని కనెక్ట్ చేయండి', mr: 'Google कनेक्ट करा' },
    'planner.importEvents': { en: 'Import events', hi: 'कार्यक्रम आयात करें', ta: 'நிகழ்வுகளை இறக்குமதி செய்யவும்', bn: 'ইভেন্ট ইমপোর্ট করুন', te: 'ఈవెంట్‌లను దిగుమతి చేయండి', mr: 'कार्यक्रम आयात करा' },
    'planner.loadError': { en: 'Could not load the planner.', hi: 'प्लानर लोड नहीं हो सका।', ta: 'திட்டமிடலை ஏற்ற முடியவில்லை.', bn: 'প্ল্যানার লোড করা যায়নি।', te: 'ప్లానర్‌ను లోడ్ చేయలేకపోయాం.', mr: 'प्लॅनर लोड करता आला नाही.' },
    'planner.showingCached': { en: 'Showing the last saved plan.', hi: 'पिछली सहेजी गई योजना दिखाई जा रही है।', ta: 'கடைசியாகச் சேமித்த திட்டம் காட்டப்படுகிறது.', bn: 'শেষ সংরক্ষিত পরিকল্পনা দেখানো হচ্ছে।', te: 'చివరిగా సేవ్ చేసిన ప్లాన్ చూపబడుతోంది.', mr: 'शेवटची जतन केलेली योजना दाखवत आहोत.' },
    'library.title': { en: 'Library', hi: 'पुस्तकालय', ta: 'நூலகம்', bn: 'লাইব্রেরি', te: 'లైబ్రరీ', mr: 'ग्रंथालय' },
    'library.addPdf': { en: 'Add PDF', hi: 'PDF जोड़ें', ta: 'PDF சேர்க்கவும்', bn: 'PDF যোগ করুন', te: 'PDF జోడించండి', mr: 'PDF जोडा' },
    'library.resources': { en: 'Study resources', hi: 'अध्ययन संसाधन', ta: 'படிப்பு வளங்கள்', bn: 'পড়াশোনার সংস্থান', te: 'అధ్యయన వనరులు', mr: 'अभ्यास साधने' },
    'library.reader': { en: 'Reader', hi: 'रीडर', ta: 'வாசிப்பான்', bn: 'রিডার', te: 'రీడర్', mr: 'रीडर' },
    'library.annotations': { en: 'Highlights and annotations', hi: 'हाइलाइट और टिप्पणियां', ta: 'முன்னிலைப்படுத்தல்கள் மற்றும் குறிப்புகள்', bn: 'হাইলাইট ও টীকা', te: 'హైలైట్‌లు మరియు గమనికలు', mr: 'हायलाइट आणि टिपणे' },
    'tools.title': { en: 'Study tools', hi: 'अध्ययन उपकरण', ta: 'படிப்பு கருவிகள்', bn: 'পড়াশোনার সরঞ্জাম', te: 'అధ్యయన సాధనాలు', mr: 'अभ्यास साधने' },
    'tools.recall': { en: 'Recall', hi: 'स्मरण', ta: 'நினைவுகூரல்', bn: 'স্মরণ', te: 'రీకాల్', mr: 'स्मरण' },
    'tools.practice': { en: 'Practice', hi: 'अभ्यास', ta: 'பயிற்சி', bn: 'অনুশীলন', te: 'అభ్యాసం', mr: 'सराव' },
    'tools.wellbeing': { en: 'Wellbeing', hi: 'कल्याण', ta: 'நல்வாழ்வு', bn: 'সুস্থতা', te: 'శ్రేయస్సు', mr: 'कल्याण' },
    'tools.guidance': { en: 'Guidance', hi: 'मार्गदर्शन', ta: 'வழிகாட்டுதல்', bn: 'নির্দেশনা', te: 'మార్గదర్శనం', mr: 'मार्गदर्शन' },
    'tools.intro': { en: 'Choose one focused workspace to keep the tools quick to scan.', hi: 'टूल्स को आसानी से देखने के लिए एक केंद्रित कार्यक्षेत्र चुनें।', ta: 'கருவிகளை விரைவாகப் பார்க்க ஒரு கவனம் செலுத்திய பணியிடத்தைத் தேர்வு செய்யவும்.', bn: 'টুলগুলো দ্রুত স্ক্যান করতে একটি ফোকাসড ওয়ার্কস্পেস বেছে নিন।', te: 'టూల్స్‌ను త్వరగా చూడటానికి ఒక ఫోకస్డ్ వర్క్‌స్పేస్ ఎంచుకోండి.', mr: 'साधने पटकन पाहण्यासाठी एक केंद्रित कार्यक्षेत्र निवडा.' },
    'currentAffairs.title': { en: 'Current affairs', hi: 'समसामयिकी', ta: 'நடப்பு நிகழ்வுகள்', bn: 'সাম্প্রতিক বিষয়', te: 'కరెంట్ అఫైర్స్', mr: 'चालू घडामोडी' },
    'community.title': { en: 'Community', hi: 'समुदाय', ta: 'சமூகம்', bn: 'সম্প্রদায়', te: 'కమ్యూనిటీ', mr: 'समुदाय' },
    'community.report': { en: 'Report', hi: 'रिपोर्ट करें', ta: 'புகார்', bn: 'রিপোর্ট', te: 'రిపోర్ట్', mr: 'तक्रार' },
    'more.title': { en: 'More', hi: 'अधिक', ta: 'மேலும்', bn: 'আরও', te: 'మరిన్ని', mr: 'अधिक' },
    'practice.timedPaper': { en: 'Timed paper', hi: 'समयबद्ध पेपर', ta: 'நேரக் கேள்வித்தாள்', bn: 'সময়বদ্ধ পেপার', te: 'సమయ పేపర్', mr: 'वेळबद्ध पेपर' },
    'practice.fullMock': { en: 'Full mock', hi: 'पूर्ण मॉक टेस्ट', ta: 'முழு மாதிரி தேர்வு', bn: 'সম্পূর্ণ মক', te: 'పూర్తి మాక్', mr: 'पूर्ण मॉक' },
    'practice.previous': { en: 'Previous', hi: 'पिछला', ta: 'முந்தையது', bn: 'আগের', te: 'మునుపటి', mr: 'मागील' },
    'practice.next': { en: 'Next', hi: 'अगला', ta: 'அடுத்து', bn: 'পরের', te: 'తదుపరి', mr: 'पुढील' },
    'practice.submit': { en: 'Submit', hi: 'जमा करें', ta: 'சமர்ப்பிக்கவும்', bn: 'জমা দিন', te: 'సమర్పించండి', mr: 'सबमिट करा' },
    'practice.mockTitle': { en: 'Full mock', hi: 'पूर्ण मॉक टेस्ट', ta: 'முழு மாதிரி தேர்வு', bn: 'সম্পূর্ণ মক', te: 'పూర్తి మాక్', mr: 'पूर्ण मॉक टेस्ट' },
    'practice.officialScoring': { en: 'Official scoring', hi: 'आधिकारिक स्कोरिंग', ta: 'அதிகாரப்பூர்வ மதிப்பீடு', bn: 'অফিশিয়াল স্কোরিং', te: 'అధికారిక స్కోరింగ్', mr: 'अधिकृत स्कोअरिंग' },
    'practice.result': { en: 'Result', hi: 'परिणाम', ta: 'முடிவு', bn: 'ফলাফল', te: 'ఫలితం', mr: 'निकाल' },
    'practice.question': { en: 'Question', hi: 'प्रश्न', ta: 'கேள்வி', bn: 'প্রশ্ন', te: 'ప్రశ్న', mr: 'प्रश्न' },
    'practice.markedForReview': { en: 'marked for review', hi: 'पुनरावलोकन के लिए चिह्नित', ta: 'மறுபரிசீலனைக்குக் குறிக்கப்பட்டது', bn: 'রিভিউয়ের জন্য চিহ্নিত', te: 'రివ్యూ కోసం గుర్తించబడింది', mr: 'पुनरावलोकनासाठी चिन्हांकित' },
    'practice.markForReview': { en: 'Mark for review', hi: 'पुनरावलोकन के लिए चिह्नित करें', ta: 'மறுபரிசீலனைக்குக் குறிக்கவும்', bn: 'রিভিউয়ের জন্য চিহ্নিত করুন', te: 'రివ్యూ కోసం గుర్తించండి', mr: 'पुनरावलोकनासाठी चिन्हांकित करा' },
    'practice.unmark': { en: 'Unmark', hi: 'चिह्न हटाएं', ta: 'குறியை நீக்கவும்', bn: 'চিহ्न সরান', te: 'గుర్తు తొలగించండి', mr: 'चिन्ह काढा' },
    'practice.saveProgress': { en: 'Save progress', hi: 'प्रगति सहेजें', ta: 'முன்னேற்றத்தைச் சேமிக்கவும்', bn: 'অগ্রগতি সংরক্ষণ করুন', te: 'ప్రగతిని సేవ్ చేయండి', mr: 'प्रगती जतन करा' },
    'practice.submitMock': { en: 'Submit mock', hi: 'मॉक जमा करें', ta: 'மாதிரியைச் சமர்ப்பிக்கவும்', bn: 'মক জমা দিন', te: 'మాక్ సమర్పించండి', mr: 'मॉक सबमिट करा' },
    'practice.noOfficialQuestions': { en: 'Verified UPSC/SSC questions are not seeded yet. Import an official paper first.', hi: 'सत्यापित UPSC/SSC प्रश्न अभी सीड नहीं किए गए हैं। पहले आधिकारिक पेपर आयात करें।', ta: 'சரிபார்க்கப்பட்ட UPSC/SSC கேள்விகள் இன்னும் சேர்க்கப்படவில்லை. முதலில் அதிகாரப்பூர்வ கேள்வித்தாளை இறக்குமதி செய்யவும்.', bn: 'যাচাইকৃত UPSC/SSC প্রশ্ন এখনও সিড করা হয়নি। আগে অফিসিয়াল পেপার ইম্পোর্ট করুন।', te: 'ధృవీకరించిన UPSC/SSC ప్రశ్నలు ఇంకా సీడ్ కాలేదు. ముందుగా అధికారిక పేపర్‌ను దిగుమతి చేయండి.', mr: 'सत्यापित UPSC/SSC प्रश्न अजून सीड केलेले नाहीत. आधी अधिकृत पेपर आयात करा.' },
    'practice.noMock': { en: 'No mock is available yet.', hi: 'अभी कोई मॉक उपलब्ध नहीं है।', ta: 'இன்னும் மாதிரி தேர்வு கிடைக்கவில்லை.', bn: 'এখনও কোনো মক পাওয়া যায়নি।', te: 'ఇంకా మాక్ అందుబాటులో లేదు.', mr: 'अजून मॉक उपलब्ध नाही.' },
    'practice.noQuestions': { en: 'No questions match this filter.', hi: 'इस फ़िल्टर से कोई प्रश्न मेल नहीं खाते।', ta: 'இந்த வடிகட்டிக்கு கேள்விகள் இல்லை.', bn: 'এই ফিল্টারে কোনো প্রশ্ন নেই।', te: 'ఈ ఫిల్టర్‌కు ప్రశ్నలు లేవు.', mr: 'या फिल्टरशी जुळणारे प्रश्न नाहीत.' },
    'practice.progressSaved': { en: 'Progress saved.', hi: 'प्रगति सहेजी गई।', ta: 'முன்னேற்றம் சேமிக்கப்பட்டது.', bn: 'অগ্রগতি সংরক্ষিত হয়েছে।', te: 'ప్రగతి సేవ్ చేయబడింది.', mr: 'प्रगती जतन झाली.' },
    'practice.mockProgressError': { en: 'Could not save mock progress.', hi: 'मॉक प्रगति सेव नहीं हो सकी।', ta: 'மாதிரி முன்னேற்றத்தைச் சேமிக்க முடியவில்லை.', bn: 'মকের অগ্রগতি সংরক্ষণ করা যায়নি।', te: 'మాక్ ప్రగతిని సేవ్ చేయలేకపోయాం.', mr: 'मॉक प्रगती जतन करता आली नाही.' },
    'practice.mockSubmitSuccess': { en: 'Mock submitted', hi: 'मॉक जमा किया गया', ta: 'மாதிரி சமர்ப்பிக்கப்பட்டது', bn: 'মক জমা হয়েছে', te: 'మాక్ సమర్పించబడింది', mr: 'मॉक सबमিট केला' },
    'practice.mockSubmitError': { en: 'Could not submit the mock.', hi: 'मॉक जमा नहीं हो सका।', ta: 'மாதிரியைச் சமர்ப்பிக்க முடியவில்லை.', bn: 'মক জমা দেওয়া যায়নি।', te: 'మాక్‌ను సమర్పించలేకపోయాం.', mr: 'मॉक सबमिट करता आला नाही.' },
    'practice.totalTime': { en: 'Total', hi: 'कुल', ta: 'மொத்தம்', bn: 'মোট', te: 'మొత్తం', mr: 'एकूण' },
    'practice.section': { en: 'Section', hi: 'अनुभाग', ta: 'பகுதி', bn: 'বিভাগ', te: 'విభాగం', mr: 'विभाग' },
    'practice.of': { en: 'of', hi: 'में से', ta: '/', bn: 'এর মধ্যে', te: 'లో', mr: 'पैकी' },
    'practice.marksPerQuestion': { en: 'marks/question', hi: 'अंक/प्रश्न', ta: 'மதிப்பெண்/கேள்வி', bn: 'নম্বর/প্রশ্ন', te: 'మార్కులు/ప్రశ్న', mr: 'गुण/प्रश्न' },
    'practice.negative': { en: 'negative', hi: 'ऋणात्मक', ta: 'எதிர்மதிப்பெண்', bn: 'নেগেটিভ', te: 'మైనస్', mr: 'नकारात्मक' },
    'practice.correct': { en: 'correct', hi: 'सही', ta: 'சரி', bn: 'সঠিক', te: 'సరైనవి', mr: 'बरोबर' },
    'practice.incorrect': { en: 'incorrect', hi: 'गलत', ta: 'தவறு', bn: 'ভুল', te: 'తప్పు', mr: 'चुकीचे' },
    'practice.unanswered': { en: 'unanswered', hi: 'अनुत्तरित', ta: 'பதிலளிக்காதவை', bn: 'উত্তরহীন', te: 'సమాధానం లేనివి', mr: 'अनुत्तरित' },
    'practice.mockSubmitted': { en: 'Mock submitted', hi: 'मॉक जमा किया गया', ta: 'மாதிரி சமர்ப்பிக்கப்பட்டது', bn: 'মক জমা হয়েছে', te: 'మాక్ సమర్పించబడింది', mr: 'मॉक सबमिट केला' },
    'common.offline': { en: 'Offline', hi: 'ऑफलाइन', ta: 'ஆஃப்லைன்', bn: 'অফলাইন', te: 'ఆఫ్‌లైన్', mr: 'ऑफलाइन' },
    'common.saveOffline': { en: 'Save for offline reading', hi: 'ऑफलाइन पढ़ने के लिए सहेजें', ta: 'ஆஃப்லைன் வாசிப்புக்குச் சேமிக்கவும்', bn: 'অফলাইনে পড়ার জন্য সংরক্ষণ করুন', te: 'ఆఫ్‌లైన్ చదవడానికి సేవ్ చేయండి', mr: 'ऑफलाइन वाचनासाठी जतन करा' },
    'common.working': { en: 'Working…', hi: 'काम हो रहा है…', ta: 'செயல்படுகிறது…', bn: 'কাজ চলছে…', te: 'పని జరుగుతోంది…', mr: 'काम सुरू आहे…' },
    'common.add': { en: 'Add', hi: 'जोड़ें', ta: 'சேர்க்கவும்', bn: 'যোগ করুন', te: 'జోడించండి', mr: 'जोडा' },
    'common.update': { en: 'Update', hi: 'अपडेट करें', ta: 'புதுப்பிக்கவும்', bn: 'আপডেট করুন', te: 'అప్‌డేట్ చేయండి', mr: 'अपडेट करा' },
    'common.open': { en: 'Open', hi: 'खोलें', ta: 'திறக்கவும்', bn: 'খুলুন', te: 'తెరవండి', mr: 'उघडा' },
    'common.previous': { en: 'Previous', hi: 'पिछला', ta: 'முந்தையது', bn: 'আগের', te: 'మునుపటి', mr: 'मागील' },
    'common.pages': { en: 'pages', hi: 'पृष्ठ', ta: 'பக்கங்கள்', bn: 'পৃষ্ঠা', te: 'పేజీలు', mr: 'पाने' },
    'common.pending': { en: 'pending', hi: 'लंबित', ta: 'நிலுவையில்', bn: 'বাকি', te: 'పెండింగ్', mr: 'प्रलंबित' },
    'common.trend': { en: 'Trend', hi: 'रुझान', ta: 'போக்கு', bn: 'প্রবণতা', te: 'ట్రెండ్', mr: 'ट्रेंड' },
    'common.estimatedRange': { en: 'Estimated range', hi: 'अनुमानित सीमा', ta: 'மதிப்பிடப்பட்ட வரம்பு', bn: 'আনুমানিক সীমা', te: 'అంచనా పరిధి', mr: 'अंदाजे श्रेणी' },
    'common.couldNotLoadAnalytics': { en: 'Could not load analytics.', hi: 'विश्लेषण लोड नहीं हो सका।', ta: 'பகுப்பாய்வை ஏற்ற முடியவில்லை.', bn: 'অ্যানালিটিক্স লোড করা যায়নি।', te: 'అనలిటిక్స్ లోడ్ కాలేదు.', mr: 'विश्लेषण लोड करता आले नाही.' },
    'currentAffairs.refresh': { en: 'Refresh official feed', hi: 'आधिकारिक फ़ीड रीफ्रेश करें', ta: 'அதிகாரப்பூர்வ ஊட்டத்தைப் புதுப்பிக்கவும்', bn: 'অফিশিয়াল ফিড রিফ্রেশ করুন', te: 'అధికారిక ఫీడ్‌ను రిఫ్రెష్ చేయండి', mr: 'अधिकृत फीड रिफ्रेश करा' },
    'currentAffairs.noUpdates': { en: 'No updates yet. Your official UPSC/SSC feed will appear here.', hi: 'अभी कोई अपडेट नहीं। आपकी आधिकारिक UPSC/SSC फ़ीड यहां दिखाई देगी।', ta: 'இன்னும் புதுப்பிப்புகள் இல்லை. அதிகாரப்பூர்வ UPSC/SSC ஊட்டம் இங்கே தோன்றும்.', bn: 'এখনও কোনো আপডেট নেই। অফিসিয়াল UPSC/SSC ফিড এখানে দেখা যাবে।', te: 'ఇంకా అప్‌డేట్‌లు లేవు. అధికారిక UPSC/SSC ఫీడ్ ఇక్కడ కనిపిస్తుంది.', mr: 'अद्याप अपडेट नाहीत. अधिकृत UPSC/SSC फीड येथे दिसेल.' },
    'currentAffairs.cached': { en: 'Showing cached updates.', hi: 'कैश किए गए अपडेट दिखाए जा रहे हैं।', ta: 'தற்காலிகமாக சேமித்த புதுப்பிப்புகள் காட்டப்படுகின்றன.', bn: 'ক্যাশ করা আপডেট দেখানো হচ্ছে।', te: 'క్యాష్ చేసిన అప్‌డేట్‌లు చూపబడుతున్నాయి.', mr: 'कॅश केलेले अपडेट दाखवत आहोत.' },
    'currentAffairs.refreshError': { en: 'Configure the official feed on the backend before refreshing.', hi: 'रीफ्रेश करने से पहले बैकएंड पर आधिकारिक फ़ीड कॉन्फ़िगर करें।', ta: 'புதுப்பிப்பதற்கு முன் பின்தளத்தில் அதிகாரப்பூர்வ ஊட்டத்தை அமைக்கவும்.', bn: 'রিফ্রেশ করার আগে ব্যাকএন্ডে অফিসিয়াল ফিড কনফিগার করুন।', te: 'రిఫ్రెష్ చేయడానికి ముందు బ్యాకెండ్‌లో అధికారిక ఫీడ్‌ను కాన్ఫిగర్ చేయండి.', mr: 'रिफ्रेश करण्यापूर्वी बॅकएंडवर अधिकृत फीड कॉन्फिगर करा.' },
    'currentAffairs.savedRead': { en: 'Saved as read', hi: 'पढ़ा हुआ सहेजा गया', ta: 'படித்ததாகச் சேமிக்கப்பட்டது', bn: 'পড়া হয়েছে হিসেবে সংরক্ষিত', te: 'చదివినట్లుగా సేవ్ చేయబడింది', mr: 'वाचलेले म्हणून जतन केले' },
    'currentAffairs.markRead': { en: 'Mark read + revise', hi: 'पढ़ा हुआ चिह्नित करें + दोहराएं', ta: 'படித்ததாகக் குறிக்கவும் + மறுபரிசீலனை', bn: 'পড়া হিসেবে চিহ্নিত করুন + রিভাইজ করুন', te: 'చదివినట్లుగా గుర్తించండి + రివైజ్ చేయండి', mr: 'वाचलेले म्हणून चिन्हांकित करा + उजळणी करा' },
    'more.intro': { en: 'Everything else for your UPSC/SSC study workflow.', hi: 'आपके UPSC/SSC अध्ययन कार्यप्रवाह की बाकी सभी सुविधाएं।', ta: 'உங்கள் UPSC/SSC படிப்பு பணிப்பாய்வின் பிற வசதிகள்.', bn: 'আপনার UPSC/SSC পড়াশোনার বাকি সব সুবিধা।', te: 'మీ UPSC/SSC స్టడీ వర్క్‌ఫ్లోలోని మిగతా ఫీచర్లు.', mr: 'तुमच्या UPSC/SSC अभ्यास कार्यप्रवाहातील इतर सर्व सुविधा.' },
    'more.notesDescription': { en: 'Text, photo and voice notes into revision material.', hi: 'टेक्स्ट, फोटो और वॉइस नोट्स को रिवीजन सामग्री में बदलें।', ta: 'உரை, புகைப்படம் மற்றும் குரல் குறிப்புகளை மறுபரிசீலனைப் பொருளாக மாற்றவும்.', bn: 'টেক্সট, ছবি ও ভয়েস নোটকে রিভিশন উপকরণে পরিণত করুন।', te: 'టెక్స్ట్, ఫోటో, వాయిస్ నోట్స్‌ను రివిజన్ మెటీరియల్‌గా మార్చండి.', mr: 'टेक्स्ट, फोटो आणि व्हॉइस नोट्सचे उजळणी साहित्यात रूपांतर करा.' },
    'more.updatesDescription': { en: 'UPSC/SSC updates and official-source refresh.', hi: 'UPSC/SSC अपडेट और आधिकारिक स्रोत रीफ्रेश।', ta: 'UPSC/SSC புதுப்பிப்புகள் மற்றும் அதிகாரப்பூர்வ மூல புதுப்பிப்பு.', bn: 'UPSC/SSC আপডেট ও অফিসিয়াল সোর্স রিফ্রেশ।', te: 'UPSC/SSC అప్‌డేట్‌లు మరియు అధికారిక సోర్స్ రిఫ్రెష్.', mr: 'UPSC/SSC अपडेट आणि अधिकृत स्रोत रिफ्रेश.' },
    'more.toolsDescription': { en: 'Recall, formulas, pacing, wellbeing and strategy.', hi: 'स्मरण, फ़ॉर्मूला, गति, कल्याण और रणनीति।', ta: 'நினைவுகூரல், சூத்திரங்கள், வேகம், நல்வாழ்வு மற்றும் உத்தி.', bn: 'স্মরণ, সূত্র, গতি, সুস্থতা ও কৌশল।', te: 'రీకాల్, ఫార్ములాలు, పేసింగ్, వెల్‌బీయింగ్ మరియు స్ట్రాటజీ.', mr: 'स्मरण, सूत्रे, गती, कल्याण आणि रणनीती.' },
    'more.libraryDescription': { en: 'PDFs, resources, highlights and annotations.', hi: 'PDF, संसाधन, हाइलाइट और टिप्पणियां।', ta: 'PDFகள், வளங்கள், முன்னிலைப்படுத்தல்கள் மற்றும் குறிப்புகள்.', bn: 'PDF, রিসোর্স, হাইলাইট ও টীকা।', te: 'PDFలు, వనరులు, హైలైట్‌లు మరియు గమనికలు.', mr: 'PDF, साधने, हायलाइट्स आणि टिपणे.' },
    'more.communityDescription': { en: 'Buddies, messaging and shared study progress.', hi: 'बडी, मैसेजिंग और साझा अध्ययन प्रगति।', ta: 'நண்பர்கள், செய்தி மற்றும் பகிரப்பட்ட படிப்பு முன்னேற்றம்.', bn: 'বাডি, মেসেজিং ও শেয়ার করা পড়াশোনার অগ্রগতি।', te: 'బడ్డీలు, మెసేజింగ్ మరియు షేర్ చేసిన స్టడీ ప్రోగ్రెస్.', mr: 'बडी, मेसेजिंग आणि शेअर केलेली अभ्यास प्रगती.' },
    'more.analyticsDescription': { en: 'Weak areas, trajectory, benchmarks and rank signals.', hi: 'कमजोर क्षेत्र, प्रगति, बेंचमार्क और रैंक संकेत।', ta: 'பலவீன பகுதிகள், முன்னேற்றம், தரநிலைகள் மற்றும் தரவரிசை அறிகுறிகள்.', bn: 'দুর্বল ক্ষেত্র, অগ্রগতি, বেঞ্চমার্ক ও র‍্যাঙ্ক সংকেত।', te: 'బలహీన ప్రాంతాలు, ట్రాజెక్టరీ, బెంచ్‌మార్క్‌లు మరియు ర్యాంక్ సిగ్నల్స్.', mr: 'कमकुवत क्षेत्रे, प्रगती, बेंचमार्क आणि रँक संकेत.' },
    'more.offlineTitle': { en: 'Offline workspace', hi: 'ऑफलाइन कार्यक्षेत्र', ta: 'ஆஃப்லைன் பணியிடம்', bn: 'অফলাইন ওয়ার্কস্পেস', te: 'ఆఫ్‌లైన్ వర్క్‌స్పేస్', mr: 'ऑफलाइन कार्यक्षेत्र' },
    'more.offlineDescription': { en: 'Cache timetable, resources, PDF pages, annotations and sleep/calendar data for the next 14 days.', hi: 'अगले 14 दिनों के लिए समय सारिणी, संसाधन, PDF पृष्ठ, टिप्पणियां और नींद/कैलेंडर डेटा कैश करें।', ta: 'அடுத்த 14 நாட்களுக்கு நேர அட்டவணை, வளங்கள், PDF பக்கங்கள், குறிப்புகள் மற்றும் தூக்கம்/காலண்டர் தரவைச் சேமிக்கவும்.', bn: 'পরবর্তী ১৪ দিনের সময়সূচি, রিসোর্স, PDF পৃষ্ঠা, টীকা ও ঘুম/ক্যালেন্ডার ডেটা ক্যাশ করুন।', te: 'తదుపరి 14 రోజులకు టైమ్‌టేబుల్, వనరులు, PDF పేజీలు, గమనికలు మరియు నిద్ర/క్యాలెండర్ డేటాను క్యాష్ చేయండి.', mr: 'पुढील 14 दिवसांसाठी वेळापत्रक, साधने, PDF पाने, टिपणे आणि झोप/कॅलेंडर डेटा कॅश करा.' },
    'more.reconnect': { en: 'Reconnect to refresh', hi: 'रीफ्रेश करने के लिए कनेक्ट करें', ta: 'புதுப்பிக்க மீண்டும் இணைக்கவும்', bn: 'রিফ্রেশ করতে আবার সংযোগ করুন', te: 'రిఫ్రెష్ చేయడానికి మళ్లీ కనెక్ట్ చేయండి', mr: 'रिफ्रेश करण्यासाठी पुन्हा कनेक्ट करा' },
    'more.downloading': { en: 'Downloading…', hi: 'डाउनलोड हो रहा है…', ta: 'பதிவிறக்குகிறது…', bn: 'ডাউনলোড হচ্ছে…', te: 'డౌన్‌లోడ్ అవుతోంది…', mr: 'डाउनलोड होत आहे…' },
    'more.downloadWorkspace': { en: 'Download workspace', hi: 'कार्यक्षेत्र डाउनलोड करें', ta: 'பணியிடத்தைப் பதிவிறக்கவும்', bn: 'ওয়ার্কস্পেস ডাউনলোড করুন', te: 'వర్క్‌స్పేస్ డౌన్‌లోడ్ చేయండి', mr: 'कार्य क्षेत्र डाउनलोड करा' },
    'more.cached': { en: 'Cached', hi: 'कैश किया गया', ta: 'சேமிக்கப்பட்டது', bn: 'ক্যাশ করা হয়েছে', te: 'క్యాష్ చేయబడింది', mr: 'कॅश केले' },
    'more.offlineConflicts': { en: 'Offline conflicts', hi: 'ऑफलाइन टकराव', ta: 'ஆஃப்லைன் முரண்பாடுகள்', bn: 'অফলাইন দ্বন্দ্ব', te: 'ఆఫ్‌లైన్ సంఘర్షణలు', mr: 'ऑफलाइन संघर्ष' },
    'more.conflictDescription': { en: 'These changes were edited on another device or while the server version changed.', hi: 'ये बदलाव किसी दूसरे डिवाइस पर या सर्वर संस्करण बदलने के दौरान किए गए हैं।', ta: 'இந்த மாற்றங்கள் மற்றொரு சாதனத்தில் அல்லது சேவையகப் பதிப்பு மாறியபோது செய்யப்பட்டன.', bn: 'এই পরিবর্তনগুলি অন্য ডিভাইসে বা সার্ভার সংস্করণ বদলানোর সময় করা হয়েছে।', te: 'ఈ మార్పులు మరొక పరికరంలో లేదా సర్వర్ వెర్షన్ మారుతున్న సమయంలో సవరించబడ్డాయి.', mr: 'हे बदल दुसऱ्या डिव्हाइसवर किंवा सर्व्हर आवृत्ती बदलताना केले गेले.' },
    'more.keepServer': { en: 'Keep server', hi: 'सर्वर वाला रखें', ta: 'சேவையகத்தை வைத்திருக்கவும்', bn: 'সার্ভার সংস্করণ রাখুন', te: 'సర్వర్ వెర్షన్ ఉంచండి', mr: 'सर्व्हर आवृत्ती ठेवा' },
    'more.keepMine': { en: 'Keep mine', hi: 'मेरा वाला रखें', ta: 'என்னுடையதை வைத்திருக்கவும்', bn: 'আমার সংস্করণ রাখুন', te: 'నా వెర్షన్ ఉంచండి', mr: 'माझी आवृत्ती ठेवा' },
    'community.heading': { en: 'Anonymous UPSC/SSC community', hi: 'गुमनाम UPSC/SSC समुदाय', ta: 'அநாமதேய UPSC/SSC சமூகம்', bn: 'বেনামী UPSC/SSC কমিউনিটি', te: 'అనామక UPSC/SSC కమ్యూనిటీ', mr: 'अनामिक UPSC/SSC समुदाय' },
    'community.postTitle': { en: 'Post title', hi: 'पोस्ट शीर्षक', ta: 'இடுகை தலைப்பு', bn: 'পোস্টের শিরোনাম', te: 'పోస్ట్ శీర్షిక', mr: 'पोस्ट शीर्षक' },
    'community.postBody': { en: 'Share a doubt, win or study tip', hi: 'अपना सवाल, जीत या अध्ययन टिप साझा करें', ta: 'சந்தேகம், வெற்றி அல்லது படிப்பு குறிப்பைப் பகிரவும்', bn: 'সন্দেহ, সাফল্য বা পড়াশোনার টিপ শেয়ার করুন', te: 'సందేహం, విజయం లేదా స్టడీ టిప్ షేర్ చేయండి', mr: 'शंका, यश किंवा अभ्यास टिप शेअर करा' },
    'community.publish': { en: 'Publish anonymous post', hi: 'गुमनाम पोस्ट प्रकाशित करें', ta: 'அநாமதேய இடுகையை வெளியிடவும்', bn: 'বেনামী পোস্ট প্রকাশ করুন', te: 'అనామక పోస్ట్ ప్రచురించండి', mr: 'अनामिक पोस्ट प्रकाशित करा' },
    'community.reportSent': { en: 'Report sent for moderation.', hi: 'रिपोर्ट मॉडरेशन के लिए भेज दी गई।', ta: 'மதிப்பாய்விற்காகப் புகார் அனுப்பப்பட்டது.', bn: 'মডারেশনের জন্য রিপোর্ট পাঠানো হয়েছে।', te: 'మోడరేషన్ కోసం రిపోర్ట్ పంపబడింది.', mr: 'मॉडरेशनसाठी तक्रार पाठवली.' },
    'community.reportError': { en: 'Could not report this post.', hi: 'इस पोस्ट की रिपोर्ट नहीं हो सकी।', ta: 'இந்த இடுகையைப் புகாரளிக்க முடியவில்லை.', bn: 'এই পোস্টটি রিপোর্ট করা যায়নি।', te: 'ఈ పోస్ట్‌ను రిపోర్ట్ చేయలేకపోయాం.', mr: 'या पोस्टची तक्रार करता आली नाही.' },
    'community.buddiesHeading': { en: 'Matched UPSC/SSC study buddies', hi: 'मिलान किए गए UPSC/SSC अध्ययन साथी', ta: 'பொருந்திய UPSC/SSC படிப்பு நண்பர்கள்', bn: 'ম্যাচ করা UPSC/SSC স্টাডি বাডি', te: 'మ్యాచ్ అయిన UPSC/SSC స్టడీ బడ్డీలు', mr: 'जुळलेले UPSC/SSC अभ्यास साथी' },
    'community.noMatches': { en: 'No new matches yet. Your exam stage helps improve matching.', hi: 'अभी कोई नया मैच नहीं। आपका परीक्षा चरण मैचिंग बेहतर करने में मदद करता है।', ta: 'இன்னும் புதிய பொருத்தங்கள் இல்லை. உங்கள் தேர்வு நிலை பொருத்தத்தை மேம்படுத்தும்.', bn: 'এখনও নতুন ম্যাচ নেই। আপনার পরীক্ষার ধাপ ম্যাচিং উন্নত করতে সাহায্য করে।', te: 'ఇంకా కొత్త మ్యాచ్‌లు లేవు. మీ పరీక్ష దశ మ్యాచ్‌ను మెరుగుపరుస్తుంది.', mr: 'अजून नवीन जुळणी नाही. तुमचा परीक्षा टप्पा जुळणी सुधारण्यास मदत करतो.' },
    'community.connect': { en: 'Connect', hi: 'जुड़ें', ta: 'இணைக்கவும்', bn: 'সংযোগ করুন', te: 'కనెక్ట్ చేయండి', mr: 'जोडा' },
    'community.requestSent': { en: 'Buddy request sent.', hi: 'बडी अनुरोध भेज दिया गया।', ta: 'நண்பர் கோரிக்கை அனுப்பப்பட்டது.', bn: 'বাডি রিকোয়েস্ট পাঠানো হয়েছে।', te: 'బడ్డీ రిక్వెస్ట్ పంపబడింది.', mr: 'बडी विनंती पाठवली.' },
    'community.incoming': { en: 'Incoming requests', hi: 'आने वाले अनुरोध', ta: 'வரும் கோரிக்கைகள்', bn: 'আসা অনুরোধ', te: 'ఇన్‌కమింగ్ రిక్వెస్ట్‌లు', mr: 'आलेल्या विनंत्या' },
    'community.request': { en: 'Aspirant request', hi: 'अभ्यर्थी अनुरोध', ta: 'தேர்வர் கோரிக்கை', bn: 'অ্যাসপির্যান্ট রিকোয়েস্ট', te: 'ఆస్పిరెంట్ రిక్వెస్ట్', mr: 'अभ्यर्थी विनंती' },
    'community.accept': { en: 'Accept', hi: 'स्वीकार करें', ta: 'ஏற்கவும்', bn: 'গ্রহণ করুন', te: 'అంగీకరించండి', mr: 'स्वीकारा' },
    'community.messagingHeading': { en: 'Buddy messaging and shared dashboard', hi: 'बडी मैसेजिंग और साझा डैशबोर्ड', ta: 'நண்பர் செய்தி மற்றும் பகிரப்பட்ட டாஷ்போர்டு', bn: 'বাডি মেসেজিং ও শেয়ার্ড ড্যাশবোর্ড', te: 'బడ్డీ మెసేజింగ్ మరియు షేర్డ్ డ్యాష్‌బోర్డ్', mr: 'बडी मेसेजिंग आणि शेअर डॅशबोर्ड' },
    'community.noBuddy': { en: 'Accept a buddy request to start messaging and share study progress.', hi: 'मैसेजिंग और अध्ययन प्रगति साझा करने के लिए बडी अनुरोध स्वीकार करें।', ta: 'செய்தி அனுப்பவும் படிப்பு முன்னேற்றத்தைப் பகிரவும் நண்பர் கோரிக்கையை ஏற்கவும்.', bn: 'মেসেজিং ও পড়াশোনার অগ্রগতি শেয়ার করতে বাডি রিকোয়েস্ট গ্রহণ করুন।', te: 'మెసేజింగ్ మరియు స్టడీ ప్రోగ్రెస్ షేర్ చేయడానికి బడ్డీ రిక్వెస్ట్ అంగీకరించండి.', mr: 'मेसेजिंग आणि अभ्यास प्रगती शेअर करण्यासाठी बडी विनंती स्वीकारा.' },
    'community.accepted': { en: 'Accepted connection', hi: 'स्वीकृत कनेक्शन', ta: 'ஏற்றுக்கொள்ளப்பட்ட இணைப்பு', bn: 'গৃহীত সংযোগ', te: 'ఆమోదించబడిన కనెక్షన్', mr: 'स्वीकृत कनेक्शन' },
    'community.messagePlaceholder': { en: 'Write a supportive message', hi: 'प्रोत्साहन संदेश लिखें', ta: 'ஆதரவான செய்தியை எழுதவும்', bn: 'উৎসাহমূলক বার্তা লিখুন', te: 'ప్రోత్సాహకరమైన సందేశం రాయండి', mr: 'प्रोत्साहनपर संदेश लिहा' },
    'community.send': { en: 'Send', hi: 'भेजें', ta: 'அனுப்பவும்', bn: 'পাঠান', te: 'పంపండి', mr: 'पाठवा' },
    'community.shareDashboard': { en: 'Share dashboard', hi: 'डैशबोर्ड साझा करें', ta: 'டாஷ்போர்டைப் பகிரவும்', bn: 'ড্যাশবোর্ড শেয়ার করুন', te: 'డ్యాష్‌బోర్డ్ షేర్ చేయండి', mr: 'डॅशबोर्ड शेअर करा' },
    'community.viewDashboard': { en: 'View dashboard', hi: 'डैशबोर्ड देखें', ta: 'டாஷ்போர்டைப் பார்க்கவும்', bn: 'ড্যাশবোর্ড দেখুন', te: 'డ్యాష్‌బోర్డ్ చూడండి', mr: 'डॅशबोर्ड पहा' },
    'community.loadError': { en: 'Could not load the community.', hi: 'कम्युनिटी लोड नहीं हो सकी।', ta: 'சமூகத்தை ஏற்ற முடியவில்லை.', bn: 'কমিউনিটি লোড করা যায়নি।', te: 'కమ్యూనిటీని లోడ్ చేయలేకపోయాం.', mr: 'कम्युनिटी लोड करता आली नाही.' },
    'community.messagingUnavailable': { en: 'Messaging is available after the request is accepted.', hi: 'रिक्वेस्ट स्वीकार होने के बाद मैसेजिंग उपलब्ध होगी।', ta: 'கோரிக்கை ஏற்றுக்கொள்ளப்பட்ட பிறகு செய்தியிடல் கிடைக்கும்.', bn: 'অনুরোধ গ্রহণের পর মেসেজিং পাওয়া যাবে।', te: 'అభ్యర్థన అంగీకరించిన తర్వాత మెసేజింగ్ అందుబాటులో ఉంటుంది.', mr: 'विनंती स्वीकारल्यानंतर मेसेजिंग उपलब्ध होईल.' },
    'community.sendError': { en: 'Could not send the message.', hi: 'मैसेज नहीं भेजा जा सका।', ta: 'செய்தியை அனுப்ப முடியவில்லை.', bn: 'বার্তা পাঠানো যায়নি।', te: 'సందేశాన్ని పంపలేకపోయాం.', mr: 'संदेश पाठवता आला नाही.' },
    'community.shareError': { en: 'Could not share the dashboard.', hi: 'डैशबोर्ड साझा नहीं हो सका।', ta: 'டாஷ்போர்டைப் பகிர முடியவில்லை.', bn: 'ড্যাশবোর্ড শেয়ার করা যায়নি।', te: 'డ్యాష్‌బోర్డ్‌ను షేర్ చేయలేకపోయాం.', mr: 'डॅशबोर्ड शेअर करता आला नाही.' },
    'community.dashboardUnavailable': { en: 'This buddy has not shared a dashboard yet.', hi: 'इस बडी ने अभी डैशबोर्ड साझा नहीं किया है।', ta: 'இந்த நண்பர் இன்னும் டாஷ்போர்டைப் பகிரவில்லை.', bn: 'এই বাডি এখনও ড্যাশবোর্ড শেয়ার করেনি।', te: 'ఈ బడ్డి ఇంకా డ్యాష్‌బోర్డ్‌ను షేర్ చేయలేదు.', mr: 'या बडीने अजून डॅशबोर्ड शेअर केलेला नाही.' },
    'community.publishError': { en: 'Could not publish the post.', hi: 'पोस्ट प्रकाशित नहीं हो सकी।', ta: 'இடுகையை வெளியிட முடியவில்லை.', bn: 'পোস্ট প্রকাশ করা যায়নি।', te: 'పోస్ట్‌ను ప్రచురించలేకపోయాం.', mr: 'पोस्ट प्रकाशित करता आली नाही.' },
    'community.requestError': { en: 'Could not send the request.', hi: 'रिक्वेस्ट नहीं भेजी जा सकी।', ta: 'கோரிக்கையை அனுப்ப முடியவில்லை.', bn: 'অনুরোধ পাঠানো যায়নি।', te: 'అభ్యర్థనను పంపలేకపోయాం.', mr: 'विनंती पाठवता आली नाही.' },
    'community.acceptError': { en: 'Could not accept the request.', hi: 'रिक्वेस्ट स्वीकार नहीं हो सकी।', ta: 'கோரிக்கையை ஏற்க முடியவில்லை.', bn: 'অনুরোধ গ্রহণ করা যায়নি।', te: 'అభ్యర్థనను అంగీకరించలేకపోయాం.', mr: 'विनंती स्वीकारता आली नाही.' },
    'library.searchPlaceholder': { en: 'Search PDFs and extracted text', hi: 'PDF और निकाले गए टेक्स्ट में खोजें', ta: 'PDFகள் மற்றும் பிரித்தெடுத்த உரையில் தேடவும்', bn: 'PDF ও এক্সট্র্যাক্ট করা টেক্সট সার্চ করুন', te: 'PDFలు మరియు ఎక్స్‌ట్రాక్ట్ చేసిన టెక్స్ట్‌లో వెతకండి', mr: 'PDF आणि काढलेल्या मजकुरात शोधा' },
    'library.empty': { en: 'Your PDFs, resources and annotations will appear here.', hi: 'आपके PDF, संसाधन और टिप्पणियां यहां दिखाई देंगी।', ta: 'உங்கள் PDFகள், வளங்கள் மற்றும் குறிப்புகள் இங்கே தோன்றும்.', bn: 'আপনার PDF, রিসোর্স ও টীকা এখানে দেখা যাবে।', te: 'మీ PDFలు, వనరులు మరియు గమనికలు ఇక్కడ కనిపిస్తాయి.', mr: 'तुमचे PDF, साधने आणि टिपणे येथे दिसतील.' },
    'library.pdfDocument': { en: 'PDF document', hi: 'PDF दस्तावेज़', ta: 'PDF ஆவணம்', bn: 'PDF ডকুমেন্ট', te: 'PDF డాక్యుమెంట్', mr: 'PDF दस्तऐवज' },
    'library.openFile': { en: 'Open PDF file', hi: 'PDF फ़ाइल खोलें', ta: 'PDF கோப்பைத் திறக்கவும்', bn: 'PDF ফাইল খুলুন', te: 'PDF ఫైల్ తెరవండి', mr: 'PDF फाइल उघडा' },
    'library.readerPage': { en: 'Page', hi: 'पृष्ठ', ta: 'பக்கம்', bn: 'পৃষ্ঠা', te: 'పేజీ', mr: 'पान' },
    'library.visualNotCached': { en: 'Visual page is not cached yet. Connect once to render this scanned page.', hi: 'दृश्य पृष्ठ अभी कैश नहीं है। इस स्कैन पृष्ठ को रेंडर करने के लिए एक बार कनेक्ट करें।', ta: 'காட்சிப் பக்கம் இன்னும் சேமிக்கப்படவில்லை. ஸ்கேன் செய்யப்பட்ட பக்கத்தை வழங்க ஒருமுறை இணைக்கவும்.', bn: 'ভিজ্যুয়াল পৃষ্ঠা এখনও ক্যাশ করা হয়নি। স্ক্যান করা পৃষ্ঠা রেন্ডার করতে একবার সংযোগ করুন।', te: 'విజువల్ పేజీ ఇంకా క్యాష్ కాలేదు. ఈ స్కాన్ చేసిన పేజీని రెండర్ చేయడానికి ఒకసారి కనెక్ట్ చేయండి.', mr: 'दृश्य पान अजून कॅश केलेले नाही. स्कॅन केलेले पान रेंडर करण्यासाठी एकदा कनेक्ट करा.' },
    'library.noReadablePages': { en: 'This PDF has no readable pages. Open the stored PDF file for scanned pages.', hi: 'इस PDF में पढ़ने योग्य पृष्ठ नहीं हैं। स्कैन पृष्ठों के लिए संग्रहीत PDF खोलें।', ta: 'இந்த PDF-ல் படிக்கக்கூடிய பக்கங்கள் இல்லை. ஸ்கேன் பக்கங்களுக்கு சேமித்த PDF-ஐத் திறக்கவும்.', bn: 'এই PDF-এ পড়ার মতো পৃষ্ঠা নেই। স্ক্যান করা পৃষ্ঠার জন্য সংরক্ষিত PDF খুলুন।', te: 'ఈ PDFలో చదవగల పేజీలు లేవు. స్కాన్ చేసిన పేజీల కోసం సేవ్ చేసిన PDFను తెరవండి.', mr: 'या PDF मध्ये वाचनीय पाने नाहीत. स्कॅन केलेल्या पानांसाठी जतन केलेले PDF उघडा.' },
    'library.annotationHint': { en: 'Annotations are saved against a page and selected-text offset, and can be edited or deleted.', hi: 'टिप्पणियां पृष्ठ और चुने गए टेक्स्ट ऑफसेट के साथ सहेजी जाती हैं और संपादित या हटाई जा सकती हैं।', ta: 'குறிப்புகள் பக்கம் மற்றும் தேர்ந்தெடுத்த உரை இடத்துடன் சேமிக்கப்படுகின்றன; திருத்தலாம் அல்லது நீக்கலாம்.', bn: 'টীকা পৃষ্ঠা ও নির্বাচিত টেক্সট অফসেটের সাথে সংরক্ষিত হয় এবং সম্পাদনা বা মুছে ফেলা যায়।', te: 'గమనికలు పేజీ మరియు ఎంచుకున్న టెక్స్ట్ ఆఫ్‌సెట్‌తో సేవ్ అవుతాయి; ఎడిట్ లేదా డిలీట్ చేయవచ్చు.', mr: 'टिपणे पान आणि निवडलेल्या मजकूर ऑफसेटसह जतन केली जातात; संपादित किंवा हटवता येतात.' },
    'library.resourceTitle': { en: 'Resource title', hi: 'संसाधन शीर्षक', ta: 'வளத்தின் தலைப்பு', bn: 'রিসোর্সের শিরোনাম', te: 'వనరుల శీర్షిక', mr: 'साधन शीर्षक' },
    'library.resourceUrl': { en: 'YouTube/article URL (optional)', hi: 'YouTube/लेख URL (वैकल्पिक)', ta: 'YouTube/கட்டுரை URL (விருப்பம்)', bn: 'YouTube/আর্টিকেল URL (ঐচ্ছিক)', te: 'YouTube/ఆర్టికల్ URL (ఐచ్ఛికం)', mr: 'YouTube/लेख URL (पर्यायी)' },
    'library.addResource': { en: 'Add resource', hi: 'संसाधन जोड़ें', ta: 'வளத்தைச் சேர்க்கவும்', bn: 'রিসোর্স যোগ করুন', te: 'వనరును జోడించండి', mr: 'साधन जोडा' },
    'library.updateResource': { en: 'Update resource', hi: 'संसाधन अपडेट करें', ta: 'வளத்தைப் புதுப்பிக்கவும்', bn: 'রিসোর্স আপডেট করুন', te: 'వనరును అప్‌డేట్ చేయండి', mr: 'साधन अपडेट करा' },
    'library.saveAnnotation': { en: 'Save annotation', hi: 'टिप्पणी सहेजें', ta: 'குறிப்பைச் சேமிக்கவும்', bn: 'টীকা সংরক্ষণ করুন', te: 'గమనికను సేవ్ చేయండి', mr: 'टिपण जतन करा' },
    'library.updateAnnotation': { en: 'Update annotation', hi: 'टिप्पणी अपडेट करें', ta: 'குறிப்பைப் புதுப்பிக்கவும்', bn: 'টীকা আপডেট করুন', te: 'గమనికను అప్‌డేట్ చేయండి', mr: 'टिपण अपडेट करा' },
    'library.quotePlaceholder': { en: 'Text to highlight (optional)', hi: 'हाइलाइट करने वाला टेक्स्ट (वैकल्पिक)', ta: 'முன்னிலைப்படுத்த வேண்டிய உரை (விருப்பம்)', bn: 'হাইলাইট করার টেক্সট (ঐচ্ছিক)', te: 'హైలైట్ చేయాల్సిన టెక్స్ట్ (ఐచ్ఛికం)', mr: 'हायलाइट करायचा मजकूर (पर्यायी)' },
    'library.notePlaceholder': { en: 'Note or explanation', hi: 'नोट या स्पष्टीकरण', ta: 'குறிப்பு அல்லது விளக்கம்', bn: 'নোট বা ব্যাখ্যা', te: 'నోట్ లేదా వివరణ', mr: 'टिपण किंवा स्पष्टीकरण' },
    'more.preparingWorkspace': { en: 'Preparing workspace metadata', hi: 'वर्कस्पेस का डेटा तैयार हो रहा है', ta: 'பணியிடத் தரவு தயாராகிறது', bn: 'ওয়ার্কস্পেসের ডেটা প্রস্তুত হচ্ছে', te: 'వర్క్‌స్పేస్ డేటా సిద్ధమవుతోంది', mr: 'वर्कस्पेस डेटा तयार होत आहे' },
    'more.downloadingMedia': { en: 'Downloading media', hi: 'मीडिया डाउनलोड हो रहा है', ta: 'மீடியா பதிவிறக்கப்படுகிறது', bn: 'মিডিয়া ডাউনলোড হচ্ছে', te: 'మీడియా డౌన్‌లోడ్ అవుతోంది', mr: 'मीडिया डाउनलोड होत आहे' },
    'more.downloadErrors': { en: 'items need retry', hi: 'आइटम दोबारा डाउनलोड करने होंगे', ta: 'உருப்படிகளை மீண்டும் முயற்சிக்க வேண்டும்', bn: 'টি আইটেম আবার চেষ্টা করতে হবে', te: 'అంశాలను మళ్లీ ప్రయత్నించాలి', mr: 'आयटम पुन्हा प्रयत्न करावे लागतील' },
    'more.cancelDownload': { en: 'Pause and resume later', hi: 'रोकें और बाद में जारी रखें', ta: 'இடைநிறுத்தி பின்னர் தொடரவும்', bn: 'থামিয়ে পরে চালিয়ে যান', te: 'ఆపి తర్వాత కొనసాగించండి', mr: 'थांबवा आणि नंतर सुरू ठेवा' },
    'focus.ambientLabel': { en: 'Ambient sound (optional)', hi: 'एंबिएंट ध्वनि (वैकल्पिक)', ta: 'சுற்றுப்புற ஒலி (விருப்பம்)', bn: 'অ্যাম্বিয়েন্ট শব্দ (ঐচ্ছিক)', te: 'పరిసర ధ్వని (ఐచ్ఛికం)', mr: 'परिसरातील आवाज (पर्यायी)' },
    'focus.ambientNone': { en: 'None', hi: 'कोई नहीं', ta: 'எதுவுமில்லை', bn: 'কোনোটিই নয়', te: 'ఏదీ కాదు', mr: 'काही नाही' },
    'focus.ambientPlaying': { en: 'is playing with this focus session.', hi: 'इस फोकस सत्र के साथ चल रहा है।', ta: 'இந்த கவன அமர்வுடன் ஒலிக்கிறது.', bn: 'এই ফোকাস সেশনের সঙ্গে চলছে।', te: 'ఈ ఫోకస్ సెషన్‌తో ప్లే అవుతోంది.', mr: 'या फोकस सत्रासोबत वाजत आहे.' },
    'focus.ambientUnavailable': { en: 'Ambient sound could not start. Your focus session is still running.', hi: 'एंबिएंट ध्वनि शुरू नहीं हो सकी। आपका फोकस सत्र जारी है।', ta: 'சுற்றுப்புற ஒலியைத் தொடங்க முடியவில்லை. உங்கள் கவன அமர்வு தொடர்கிறது.', bn: 'অ্যাম্বিয়েন্ট শব্দ শুরু করা যায়নি। আপনার ফোকাস সেশন চলছে।', te: 'పరిసర ధ్వని ప్రారంభం కాలేదు. మీ ఫోకస్ సెషన్ కొనసాగుతోంది.', mr: 'परिसरातील आवाज सुरू होऊ शकला नाही. तुमचे फोकस सत्र सुरू आहे.' },
    'library.previousPage': { en: 'Previous', hi: 'पिछला', ta: 'முந்தையது', bn: 'আগের', te: 'మునుపటి', mr: 'मागील' },
    'library.nextPage': { en: 'Next', hi: 'अगला', ta: 'அடுத்து', bn: 'পরের', te: 'తదుపరి', mr: 'पुढील' },
    'library.singlePage': { en: 'Single page', hi: 'एक पृष्ठ', ta: 'ஒற்றைப் பக்கம்', bn: 'এক পৃষ্ঠা', te: 'ఒక పేజీ', mr: 'एक पान' },
    'library.continuousText': { en: 'Continuous text', hi: 'सतत टेक्स्ट', ta: 'தொடர்ச்சியான உரை', bn: 'ধারাবাহিক টেক্সট', te: 'నిరంతర పాఠ్యం', mr: 'सलग मजकूर' },
    'library.searchInside': { en: 'Search inside this PDF', hi: 'इस PDF में खोजें', ta: 'இந்த PDF-இல் தேடவும்', bn: 'এই PDF-এ খুঁজুন', te: 'ఈ PDFలో వెతకండి', mr: 'या PDF मध्ये शोधा' },
    'library.noMatches': { en: 'No text matches found in this PDF.', hi: 'इस PDF में कोई टेक्स्ट मिलान नहीं मिला।', ta: 'இந்த PDF-இல் உரை பொருத்தம் இல்லை.', bn: 'এই PDF-এ কোনো টেক্সট মেলেনি।', te: 'ఈ PDFలో టెక్స్ట్ సరిపోలికలు లేవు.', mr: 'या PDF मध्ये मजकूर जुळला नाही.' },
    'library.goToPage': { en: 'Go to page', hi: 'पृष्ठ पर जाएं', ta: 'பக்கத்திற்குச் செல்லவும்', bn: 'পৃষ্ঠায় যান', te: 'పేజీకి వెళ్లండి', mr: 'पानावर जा' },
    'library.noExtractedText': { en: 'Continuous text is available after the PDF text is extracted.', hi: 'PDF टेक्स्ट निकालने के बाद सतत टेक्स्ट उपलब्ध होगा।', ta: 'PDF உரை எடுக்கப்பட்ட பிறகு தொடர்ச்சியான உரை கிடைக்கும்.', bn: 'PDF টেক্সট এক্সট্রাক্ট হওয়ার পরে ধারাবাহিক টেক্সট পাওয়া যাবে।', te: 'PDF టెక్స్ట్ తీసిన తర్వాత నిరంతర పాఠ్యం అందుబాటులో ఉంటుంది.', mr: 'PDF मजकूर काढल्यानंतर सलग मजकूर उपलब्ध होईल.' },
} as const satisfies StringCatalog;

/** The union of every known string key in the shipped catalog. */
export type StringKey = keyof typeof stringCatalog;

/** Type guard: narrows an arbitrary string to a known catalog key. */
export function isStringKey(key: string): key is StringKey {
    return Object.prototype.hasOwnProperty.call(stringCatalog, key);
}

// Re-export for convenience so consumers can import the value type alongside the catalog.
export type { LocalizedString };
