import React, { useCallback, useEffect, useMemo, useState } from 'react';
import { ActivityIndicator, Pressable, StyleSheet, Text, View } from 'react-native';

import { getAnalyticsDashboard } from '@/api/upscProduct';
import type { MoreStackScreenProps } from '@/navigation/types';
import { Action, Body, Card, Chip, Eyebrow, FeatureScreen, Heading, Muted, featureStyles, palette } from '@/screens/design/FeatureUi';

type Item = Record<string, unknown>;
const asItem = (value: unknown): Item => value && typeof value === 'object' ? value as Item : {};
const valueOf = (item: Item): number => { const value = item.normalizedPercent ?? item.scorePercent ?? item.score ?? item.value; return typeof value === 'number' ? Math.max(0, Math.min(100, value)) : 0; };

export function AnalyticsDrilldownScreen({ navigation }: MoreStackScreenProps<'AnalyticsDrilldown'>): React.JSX.Element {
    const [range, setRange] = useState<30 | 90 | 0>(90); const [data, setData] = useState<Awaited<ReturnType<typeof getAnalyticsDashboard>> | null>(null); const [selected, setSelected] = useState<Item | null>(null); const [error, setError] = useState<string | null>(null);
    const load = useCallback(async () => { setError(null); try { setData(await getAnalyticsDashboard(range || undefined)); } catch (reason) { setError(reason instanceof Error ? reason.message : 'Analytics could not load.'); } }, [range]); useEffect(() => { void load(); }, [load]);
    const points = useMemo(() => (Array.isArray(data?.points) ? data.points.map(asItem) : []), [data?.points]); const weak = useMemo(() => (Array.isArray(data?.weakAreas) ? data.weakAreas.map(asItem) : []), [data?.weakAreas]); const max = Math.max(1, ...points.map(valueOf)); const chosen = selected ?? points.at(-1) ?? null;
    return <FeatureScreen title="Score trajectory" subtitle={`Last ${range || 'all'} days • ${points.length} assessed papers`}><View style={featureStyles.row}>{([30, 90, 0] as const).map((item) => <Chip key={item} label={item ? `${item}D` : 'All'} selected={range === item} onPress={() => setRange(item)} />)}</View>{!data && !error ? <ActivityIndicator color={palette.brand} /> : null}{error ? <Card tone="warning"><Body>{error}</Body><Action label="Retry" secondary onPress={() => void load()} /></Card> : null}<Card><Heading>Scores over time</Heading><View style={styles.chart}>{points.slice(-8).map((item, index) => <Pressable key={index} accessibilityRole="button" onPress={() => setSelected(item)} style={styles.column}><View style={[styles.bar, { height: Math.max(10, valueOf(item) / max * 130), backgroundColor: chosen === item ? palette.brand : '#dbeafe' }]} /><Text style={styles.axis}>{String(item.date ?? item.createdAt ?? index + 1).slice(0, 1)}</Text></Pressable>)}</View></Card>{chosen ? <Card tone="brand"><Heading>{String(chosen.title ?? chosen.source ?? chosen.date ?? 'Selected paper')}</Heading><Body>{Math.round(valueOf(chosen))}% score • {String(chosen.durationMin ?? chosen.timeTakenMin ?? 'time not recorded')} minutes</Body><Action label="Open paper review →" secondary onPress={() => navigation.getParent()?.navigate('Practice', { screen: 'ExternalPaperReview' })} /></Card> : null}{weak[0] ? <Card tone="success"><Eyebrow>BIGGEST OPPORTUNITY</Eyebrow><Heading>{String(weak[0].topicName ?? weak[0].subjectName ?? weak[0].name ?? 'Priority topic')}</Heading><Body>{Math.round(valueOf(weak[0]))}% current signal • connect this with revision cycles.</Body><Action label="See linked chapters →" secondary onPress={() => navigation.getParent()?.navigate('Plan')} /></Card> : null}<Card tone="revision"><Heading>Study-cohort benchmark</Heading>{data?.benchmark ? <Body>Above {String(asItem(data.benchmark).percentile ?? asItem(data.benchmark).estimatedPercentile ?? '—')}% of similar active learners. Private—not a rank prediction.</Body> : <Muted>Benchmark appears after enough comparable study activity.</Muted>}</Card><Action label="Back to overview" secondary onPress={() => navigation.goBack()} /></FeatureScreen>;
}

const styles = StyleSheet.create({ chart: { height: 180, flexDirection: 'row', alignItems: 'flex-end', justifyContent: 'space-around', paddingTop: 16 }, column: { flex: 1, alignItems: 'center', justifyContent: 'flex-end', height: '100%' }, bar: { width: 22 }, axis: { color: palette.muted, fontSize: 10, marginTop: 5 } });
