import React, { useCallback, useEffect, useMemo, useState } from 'react';
import { ActivityIndicator, Pressable, StyleSheet, Text, View } from 'react-native';

import { getAnalyticsDashboard } from '@/api/upscProduct';
import type { MoreStackScreenProps } from '@/navigation/types';
import { interpolate, useTranslation } from '@/localization';
import { Action, Body, Card, Chip, Eyebrow, FeatureScreen, Heading, Muted, featureStyles, palette } from '@/screens/design/FeatureUi';

type Item = Record<string, unknown>;
const asItem = (value: unknown): Item => value && typeof value === 'object' ? value as Item : {};
const valueOf = (item: Item): number => { const value = item.normalizedPercent ?? item.scorePercent ?? item.score ?? item.value; return typeof value === 'number' ? Math.max(0, Math.min(100, value)) : 0; };

export function AnalyticsDrilldownScreen({ navigation }: MoreStackScreenProps<'AnalyticsDrilldown'>): React.JSX.Element {
    const t = useTranslation();
    const [range, setRange] = useState<30 | 90 | 0>(90); const [data, setData] = useState<Awaited<ReturnType<typeof getAnalyticsDashboard>> | null>(null); const [selected, setSelected] = useState<Item | null>(null); const [error, setError] = useState<string | null>(null);
    const load = useCallback(async () => { setError(null); try { setData(await getAnalyticsDashboard(range || undefined)); } catch (reason) { setError(reason instanceof Error ? reason.message : t('drilldown.loadError')); } }, [range, t]); useEffect(() => { void load(); }, [load]);
    const points = useMemo(() => (Array.isArray(data?.points) ? data.points.map(asItem) : []), [data?.points]); const weak = useMemo(() => (Array.isArray(data?.weakAreas) ? data.weakAreas.map(asItem) : []), [data?.weakAreas]); const max = Math.max(1, ...points.map(valueOf)); const chosen = selected ?? points.at(-1) ?? null;
    return <FeatureScreen title={t('drilldown.title')} subtitle={`${range ? interpolate(t('drilldown.lastDays'), { days: range }) : t('library.all')} • ${interpolate(t('drilldown.papers'), { count: points.length })}`}><View style={featureStyles.row}>{([30, 90, 0] as const).map((item) => <Chip key={item} label={item ? interpolate(t('drilldown.days'), { days: item }) : t('library.all')} selected={range === item} onPress={() => setRange(item)} />)}</View>{!data && !error ? <ActivityIndicator color={palette.brand} /> : null}{error ? <Card tone="warning"><Body>{error}</Body><Action label={t('common.retry')} secondary onPress={() => void load()} /></Card> : null}<Card><Heading>{t('drilldown.scoresOverTime')}</Heading><View style={styles.chart}>{points.slice(-8).map((item, index) => <Pressable key={index} accessibilityRole="button" onPress={() => setSelected(item)} style={styles.column}><View style={[styles.bar, { height: Math.max(10, valueOf(item) / max * 130), backgroundColor: chosen === item ? palette.brand : '#dbeafe' }]} /><Text style={styles.axis}>{String(item.date ?? item.createdAt ?? index + 1).slice(0, 1)}</Text></Pressable>)}</View></Card>{chosen ? <Card tone="brand"><Heading>{String(chosen.title ?? chosen.source ?? chosen.date ?? t('drilldown.selectedPaper'))}</Heading><Body>{interpolate(t('drilldown.scoreLine'), { score: Math.round(valueOf(chosen)) })} • {chosen.durationMin ?? chosen.timeTakenMin ? interpolate(t('today.minutes'), { m: String(chosen.durationMin ?? chosen.timeTakenMin) }) : t('drilldown.timeNotRecorded')}</Body><Action label={t('drilldown.openReview')} secondary onPress={() => navigation.getParent()?.navigate('Practice', { screen: 'ExternalPaperReview' })} /></Card> : null}{weak[0] ? <Card tone="success"><Eyebrow>{t('drilldown.biggestOpportunity')}</Eyebrow><Heading>{String(weak[0].topicName ?? weak[0].subjectName ?? weak[0].name ?? t('drilldown.priorityTopic'))}</Heading><Body>{interpolate(t('drilldown.weakLine'), { score: Math.round(valueOf(weak[0])) })}</Body><Action label={t('drilldown.seeChapters')} secondary onPress={() => navigation.getParent()?.navigate('Plan')} /></Card> : null}<Card tone="revision"><Heading>{t('drilldown.benchmark')}</Heading>{data?.benchmark ? <Body>{interpolate(t('drilldown.benchmarkLine'), { percent: String(asItem(data.benchmark).percentile ?? asItem(data.benchmark).estimatedPercentile ?? '—') })}</Body> : <Muted>{t('drilldown.benchmarkPending')}</Muted>}</Card><Action label={t('drilldown.back')} secondary onPress={() => navigation.goBack()} /></FeatureScreen>;
}

const styles = StyleSheet.create({ chart: { height: 180, flexDirection: 'row', alignItems: 'flex-end', justifyContent: 'space-around', paddingTop: 16 }, column: { flex: 1, alignItems: 'center', justifyContent: 'flex-end', height: '100%' }, bar: { width: 22 }, axis: { color: palette.muted, fontSize: 10, marginTop: 5 } });
